### ISSUE TITLE
SP_DIR variable incorrect

### ISSUE THREAD

**Issue by matt-chan** [conda/conda-build#3149] opened 2018-09-14 06:17 UTC
### Actual Behavior

$SP_DIR is set to `python2.7/site-packages`, even when the interpreter is 3.x. 
$PY_VER is also 2.7 in a 3.x build. 

### Expected Behavior

$SP_DIR (and $PY_VER?) should match the build interpreter version. 

### Steps to Reproduce

set Python > 3 in build/run requirements. 
echo $SP_DIR

##### `Output of conda info`

```
$ conda info

     active environment : py36-gbasis
    active env location : /<home>/miniconda2/envs/py36-gbasis
            shell level : 1
       user config file : /<home>/.condarc
 populated config files : /<home>/.condarc
          conda version : 4.5.11
    conda-build version : 3.14.4
         python version : 2.7.14.final.0
       base environment : /<home>/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /<home>/miniconda2/pkgs
                          /<home>/.conda/pkgs
       envs directories : /<home>/miniconda2/envs
                          /<home>/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/2.7.14 Linux/3.10.0-862.11.6.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by msarahan** [comment] 2018-09-14 14:32
I'm pretty sure this is the same root cause as https://github.com/conda/conda-build/issues/1028

I'm closing this issue to consolidate discussion there.

**Closed by msarahan** 2018-09-14 14:32 UTC
