### ISSUE TITLE
Specifying multiple Python versions fails to build

### ISSUE THREAD

**Issue by rwhitt2049** [conda/conda-build#2049] opened 2017-05-20 02:16 UTC
Platform: Windows 7
Conda: 4.3.18
Conda-build: 2.1.15
Python: 3.6.1

When I try to specify multiple Python versions using the `--python` flag, I get an `AttributeError`
```cmd
E:\Python\cat-feedstocks\stratus\recipe>conda build --python 3.5 --python 3.6 .
Traceback (most recent call last):
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\Scripts\conda-build-
script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Users\____\AppData\Local\Continuum\Miniconda3\lib\site-packages\co
nda_build\cli\main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\lib\site-packages\co
nda_build\cli\main_build.py", line 273, in execute
    config = Config(**args.__dict__)
  File "C:\Users\____\AppData\Local\Continuum\Miniconda3\lib\site-packages\co
nda_build\config.py", line 47, in __init__
    self.set_keys(**kwargs)
  File "C:\Users\____\AppData\Local\Continuum\Miniconda3\lib\site-packages\co
nda_build\config.py", line 71, in set_keys
    self.CONDA_PY = int(env('python', "%s%s" % (sys.version_info.major, sys.vers
ion_info.minor))
AttributeError: 'list' object has no attribute 'replace'
```

A related issue. When I try to specify all Python versions using `--python all`, I get a `ValueError`

```cmd
E:\Python\cat-feedstocks\stratus\recipe>conda build --python all .
Traceback (most recent call last):
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\Scripts\conda-build-script.py", line 5,
in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda_build\cli\main_b
uild.py", line 334, in main
    execute(sys.argv[1:])
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda_build\cli\main_b
uild.py", line 273, in execute
    config = Config(**args.__dict__)
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda_build\config.py"
, line 47, in __init__
    self.set_keys(**kwargs)
  File "C:\Users\_____\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda_build\config.py"
, line 72, in set_keys
    .replace('.', ''))
ValueError: invalid literal for int() with base 10: 'all'
```

**Comment by msarahan** [comment] 2017-05-22 14:42
Duplicate of #1316 - please see discussion at that issue.

Conda-build 3 has support for matrix builds.  You can try a preview release from the conda-canary channel:

conda update conda-build -c conda-canary

Docs for conda-build 3 new features at https://github.com/conda/conda-docs/pull/414

**Closed by msarahan** 2017-05-22 14:42 UTC
