### ISSUE TITLE
Py_ENABLE_SHARED config_var should print 1, not 0

### ISSUE THREAD

**Issue by btovar** [conda/conda-build#2738] opened 2018-03-07 13:37 UTC
With miniconda3:

% python3 -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('Py_ENABLE_SHARED'))"
0

But it should be 1, as a shared library is built in /prefix/miniconda/lib/libpython3.6m.so

We noticed this problem when using python3-config --ldflags, where a directory with static libraries is included which causes a module based on swig to fail to compile.

**Comment by mingwandroid** [comment] 2018-03-07 14:04
This is a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1761

> .. as a shared library is built in /prefix/miniconda/lib/libpython3.6m.so

We do build the shared library, but the Python interpreter does not use it. We build it only for projects that want to embed Python as a shared library.

> We noticed this problem when using python3-config --ldflags

`python3-config` is used for embedding a Python interpreter in another program, not for getting the flags to use for building extension modules. For that you should use:

python -c "import sysconfig; print(sysconfig.get_config_vars('LDSHARED'))"``

**Closed by mingwandroid** 2018-03-07 14:04 UTC

**Comment by btovar** [comment] 2018-03-07 14:11
Great, thanks for letting us know.

**Comment by gilescope** [comment] 2020-06-30 16:15
maybe conda should package two pythons one built one way and one built the other? At the moment it feels like a complete fail.

**Comment by mingwandroid** [comment] 2020-06-30 16:44
@gilescope, why do you describe it as "a complete fail"? The recommended way to build python interpreters on Unix is statically. Please avoid being unkind when you reply as you were earlier. We are humans, doing our best, and perhaps, you know, we do things for the right reasons, in general.

**Comment by btovar** [comment] 2020-06-30 17:14
I would like to add that @mingwandroid recommendation  `python -c "import sysconfig; print(sysconfig.get_config_vars('LDSHARED'))"` did work for us.

**Comment by mingwandroid** [comment] 2020-06-30 19:36
Thanks @bttovar, python-config in python 3.8 is capable of making this distinction now too, so upstream were aware of this issue and have taken the appropriate steps to address it nicely.

`$ /opt/conda/bin/python3-config --help`
.. gives:
`Usage: /opt/conda/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed`

`$ /opt/conda/bin/python3-config --ldflags`
.. gives:
`-L/opt/conda/lib/python3.8/config-3.8-x86_64-linux-gnu -L/opt/conda/lib  -lcrypt -lpthread -ldl  -lutil -lrt -lm -lm`

while:

`$ /opt/conda/bin/python3-config --ldflags --embed`
.. gives:
`-L/opt/conda/lib/python3.8/config-3.8-x86_64-linux-gnu -L/opt/conda/lib -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lrt -lm -lm`

Cheers!
