### ISSUE TITLE
add happy birday in package name?

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#2305] opened 2017-08-23 02:16 UTC
(Ok, so the title is just a joke)

Hi,
I am using 
```
               platform : osx-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : 3.0.10
```

and got very weird filename `ambertools_tempfile-0.0-py27hbd15016_0.tar.bz2`
What does `py27hbd15016_0` mean? (hbd='happy birthday'?)

So here is the story:
the 
`conda build --output receipt/ --py 2.7` return that filename while there is another filename in
`conda-bld/osx-64/ambertools-0.0-py27h2e80bc7_0.tar.bz2`

**Comment by msarahan** [comment] 2017-08-23 12:35
Duplicate of https://github.com/conda/conda-build/issues/2256 - please see that issue for explanation.  If you have further questions after reading that, I'm happy to answer them.

**Comment by msarahan** [comment] 2017-08-23 12:35
Closing this issue to consolidate discussion at #2256 - please follow up there.

**Closed by msarahan** 2017-08-23 12:35 UTC
