### ISSUE TITLE
assertion hit about downloading source file.

### ISSUE THREAD

**Issue by bkreider** [conda/conda-build#1620] opened 2017-01-05 01:11 UTC
```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 312, in main
    execute(sys.argv[1:])
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 304, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 86, in build
    need_source_download=need_source_download, config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1427, in build_tree
    config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 949, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

Possibly caused by using `--dirty`?  I tried without --dirty and it worked fine.  Am i using dirty wrong?

**Comment by bkreider** [comment] 2017-01-05 01:26
it's not working yet, but it looks like this:

```
package:
  name: mosh
  version: 1.26

source:
  url: https://mosh.org/mosh-1.2.6.tar.gz

requirements:
  build:
    - pkg-config
    - protobuf ==3.0

  run:
    - protobuf ==3.0

about:
  home: https://mosh.org/
  license: GPLv3 
```

**Comment by msarahan** [comment] 2017-01-05 02:11
Where did you find this == syntax?  That appears to be the problem.  Not sure why it's leading to a failed download message.  Probably the parsing is failing, but the exception is getting masked.

those should be something like:

protobuf 3.0.*

**Comment by bkreider** [comment] 2017-01-05 12:19
I never get the version comparisons correct between conda CLI, meta.yaml, and the environment specs.  I have to google for the correct ones each time.  But I fixed the version and it still breaks using dirty. 

Here is how i try to build:  `conda build . -c bkreider --keep-old-work --dirty`

I downloaded protobuf 3.0.0 from conda-forge and uploaded it to bkreider to prevent conda-build from pulling down other packages from conda-forge because i only want it to get protobuf from a custom channel and everything else should come from defaults.  

I'm most likely doing something wrong, but I assume an assertion is a bug.

**Comment by msarahan** [comment] 2017-01-05 14:20
``--dirty`` and ``--keep-old-work`` is redundant.  ``--dirty`` is a superset of ``--keep-old-work`` - it provides an environment variable, ``DIRTY`` in your build.sh or bld.bat script, so that you can skip over parts of the build.  It also reuses the latest build folder.

It does seem to be an issue with ``--dirty``.  I can reproduce your error with just that flag.  I can't reproduce on master, though, so it might already be fixed.  Can you explain why you think you need to use that?  Most often, that flag is there to skip really long parts of builds when debugging a recipe.  It is not necessary to use it to keep the output of recipes that are failing to build - they are not automatically cleaned up.

**Comment by bkreider** [comment] 2017-01-05 15:32
I don't really know which flag to use.  I knew i would have lots of trouble with the recipe, so i wanted to manually run commands in the directories to reproduce.

**Comment by msarahan** [comment] 2017-01-05 15:35
OK.  Just let it fail, and then your stuff will be in the build folder - something like ```<your_recipe_folder_name>_<timestamp>```, which lives in croot, which is by default ``<miniconda root>/conda-bld``

**Comment by msarahan** [comment] 2017-01-10 15:26
This assertion and the ``--dirty`` flag should be fixed by https://github.com/conda/conda-build/pull/1630/files - I'm going to close this issue for now, but please reopen it or post a new issue if the problem shows up after the 2.1.1 release.

**Closed by msarahan** 2017-01-10 15:26 UTC
