### ISSUE TITLE
Error using `curl` with `conda-build` 2.0.0

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1314] opened 2016-09-02 17:29 UTC
Just encountered an issue with `conda-build` version `2.0.0`s installation of `conda-forge`'s `curl`. So not sure where the fault lies, but am going to start here as I do not encounter this issue with `conda-build` version `1.21.14`. Also do not see this issue when simply installing `curl` into a clean environment and using it.

Please see this build [log](https://circleci.com/gh/mshunshin/opencv-feedstock/3) for details about this problem.

**Comment by msarahan** [comment] 2016-09-02 17:35
I'd guess it has something to do with

```
WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:Build prefix failed with prefix length 255
WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:Error was: 
WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:ERROR: placeholder '/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: conda-forge::ncurses-5.9-8

WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:Falling back to legacy prefix length of 80 characters.
WARNING:/opt/conda/lib/python3.5/site-packages/conda_build/build.py:Your package will not install into prefixes > 80 characters.
```

That is intended to be the compatibility path for the longer prefix length.  It may be messing up and looking in the (incompletely installed) earlier environment.  I have tests for this sort of thing, but probably could use more.  

This might be related to #1310

**Comment by jakirkham** [comment] 2016-09-02 17:48
So that is for `ncurses`. I tried this simple test with `curl` and a couple things some with and some without `ncurse`, but seem to be unable to isolate it ATM.

```meta.yaml
# test/meta.yaml

package:
  name: test
  version: 0

build:
  detect_binary_files_with_prefix: true   # Tried with and without.
  script: curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE

requirements:
  build:
    - curl
    - ncurse   # Tried with and without.
```

**Comment by msarahan** [comment] 2016-09-02 19:56
Sorry, I tried to reproduce this, but can't.  I've tried with Continuum's docker image, which seems to always bring in openssl from defaults.  I've also tried with Conda-forge's linux-anvil.  Both worked fine for me.  With both of them, I see the warning, but both are able to use curl successfully.  Might this be the system curl on the CI getting in the way somehow?  That doesn't make much sense to me, since CircleCI should be using CF's docker image, right?  How else can this be reproduced?

**Comment by jakirkham** [comment] 2016-09-02 21:24
Really, I was able to reproduce it with that docker image just by trying to build OpenCV. Have you pulled recently?

PS - The example above was an attempt to reproduce it that failed.

**Comment by msarahan** [comment] 2016-09-02 21:44
I cloned the repo that you linked above: https://github.com/mshunshin/opencv-feedstock/

I had no previous linux-anvil, so yes, the one I obtained was fresh.

**Comment by edurand** [comment] 2016-09-07 11:06
I have the same issues. Downgrade to conda-build 1.20.

**Comment by msarahan** [comment] 2016-09-07 12:08
@edurand are there any reproducible steps you can tell us?  I'd like to fix this, but since I haven't been able to reproduce it, I don't know where to start.

**Comment by jakirkham** [comment] 2016-09-26 17:51
> I cloned the repo that you linked above: https://github.com/mshunshin/opencv-feedstock/

Did you test the PR ( https://github.com/conda-forge/opencv-feedstock/pull/29 ), @msarahan, or just `master`?

**Comment by shadowwalkersb** [comment] 2016-09-26 18:03
I am not sure if this is related, but in case it helps, here it goes, https://github.com/conda-forge/staged-recipes/pull/1658#issuecomment-249627140.

**Comment by msarahan** [comment] 2016-09-26 18:45
@jakirkham I tested master of @mshunshin at the time, because that is what the PR was based on.  To be completely clear, I did not have an opencv-feedstock clone locally.  I cloned https://github.com/mshunshin/opencv-feedstock/ and tried to build it with the conda-forge docker image.

**Comment by msarahan** [comment] 2016-09-26 18:48
@shadowwalkersb I don't think that's related.  Thanks anyway.  I am not clear what your problem is, but I'd start by trying to figure out what your library load paths are.  You might need to add something like 

```
CFLAGS=-L$PREFIX/lib
```

**Comment by msarahan** [comment] 2018-01-31 23:45
Closing as resolved - we haven't seen issues in a long time.  Happy to reopen if they recur.

**Closed by msarahan** 2018-01-31 23:45 UTC
