### ISSUE TITLE
incorrect logging "Multiple meta files found" 

### ISSUE THREAD

**Issue by VitaliyaIoffe** [conda/conda-build#4705] opened 2023-01-11 13:26 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

During conda-build according to the https://github.com/conda/conda-build/blob/main/conda_build/utils.py#L1245 wrong information would be printed. `Multiple meta files found.` in case when only one meta file found. Looks like we need just to delete the logging https://github.com/conda/conda-build/blob/main/conda_build/utils.py#L1246

**Comment by travishathaway** [comment] 2023-01-18 10:04
Hi @VitaliyaIoffe,

Thank you very much for filing this bug report. Below, I'm going to explain what I think is going on and why I think this actually is not a bug.

I will admit, line 1245  is a little misleading. All found meta files are actually collected earlier in a variable called `results`. You can see that the function returns earlier if that list is either empty or only contains a single element.

By the time we get to line 1245, we already know that multiple meta files were found, and we are now just trying to figure out the best one to return and use. This is what that `metas` list is used for. We try to find a single meta file at the root of the recipe folder, and if we don't find anything, we simply raise an exception.

Provided that is true, I believe it is perfectly reasonable and correct for us to show the log message that we do. Have you found that even when a single meta file is defined in the recipe that you still receive this warning? Have you also checked any sub-directories that may contain these files? If there really is only  one meta file and this warning still appears, then this would truly be a bug.

I hope this make sense 😅 . I will go ahead and close this issue as I do not believe this is a bug. But, if you disagree, please reopen this issue and let me know why or add more information about your recipe.

Thank you,

**Closed by travishathaway** 2023-01-18 10:04 UTC
Labels: type::bug
