### ISSUE TITLE
Crash in post-processing `patchelf`

### ISSUE THREAD

**Issue by bgruening** [conda/conda-build#1411] opened 2016-09-28 06:53 UTC
The latest release crashes with the following error for some (pre-compiled) binaries.

```
Fixing permissions
cannot find section .dynamic
Traceback (most recent call last):
  File "/home/bag/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1004, in build_tree
    config=recipe_config)
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 714, in build
    croot=config.croot)
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 399, in post_build
    mk_relative(m, f, prefix)
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 366, in mk_relative
    mk_relative_linux(f, prefix=prefix, rpaths=m.get_value('build/rpaths', ['lib']))
  File "/home/bag/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 315, in mk_relative_linux
    existing = check_output([patchelf, '--print-rpath', elf]).decode('utf-8').splitlines()[0]
  File "/home/bag/miniconda2/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/bag/miniconda2/bin/patchelf', '--print-rpath', '/home/bag/miniconda2/conda-bld/searchgui_1475044759195/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/searchgui-3.1.1-0/resources/Comet/linux/comet.exe']' returned non-zero exit status 1
```

Can be related to these changes: https://github.com/conda/conda-build/commit/39503ec42da8d71d16f9ce4cf050abe507f7b2b9

**Comment by mingwandroid** [comment] 2016-09-28 08:30
Why is a Linux executable so named? i.e. ending with `.exe`? Can you show the result of:

`file /home/bag/miniconda2/conda-bld/searchgui_1475044759195/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/searchgui-3.1.1-0/resources/Comet/linux/comet.exe`

**Comment by mingwandroid** [comment] 2016-09-28 08:34
@msarahan, I guess we need to catch the check_output exception here and not bother trying to fix rpaths for things that don't have them?

**Comment by bgruening** [comment] 2016-09-28 10:42
Its a binary and I have no clue why it is names `exe` it's Proteomics, these tools are crazy :(
```
bag@bag ~ % file /home/bag/miniconda2/conda-bld/searchgui_1475044759195/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/searchgui-3.1.1-0/resources/Comet/linux/comet.exe
/home/bag/miniconda2/conda-bld/searchgui_1475044759195/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/searchgui-3.1.1-0/resources/Comet/linux/comet.exe: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.18, BuildID[sha1]=4bebd650dd3f052d1c87be394905ccb589c675a7, not stripped

````

**Comment by msarahan** [comment] 2016-09-28 12:06
Yes, we need better error handling somehow.  This appears to be a repackaged bundled executable, so it is one that probably triggers the search logic, but the search fails ungracefully.  For now, a workaround would be to modify your recipe so that conda does not try to do the RPATH stuff.  specifically:

```
build:
  ignore_prefix_files:
    - share/searchgui-3.1.1-0/resources/Comet/linux/comet.exe
```

More info at http://conda.pydata.org/docs/building/meta-yaml.html#ignore-prefix-files

**Comment by mj-harvey** [comment] 2016-09-30 07:28
(Originally opened as #1417, but a dup of this)
  
Hi,

We build a conda package including statically linked executables.
Recently, the conda build process has started failing because patchelf errors when called against a static binary:

$ patchelf --version
patchelf 0.9
$ file a.out
a.out: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5409b9978f2e5a5155090e1ac3d656f282848ad1, not stripped
$ patchelf --print-rpath a.out
cannot find section .dynamic
$ echo $?
1

See the travis build log at https://s3.amazonaws.com/archive.travis-ci.org/jobs/163653211/log.txt for an example

This seems to be a regression in conda-build, (it was working until a few days ago) but I haven't had opportunity yet to track down the change.

**Comment by mingwandroid** [comment] 2016-09-30 07:55
I'm travelling and without Linux so this is untested: https://github.com/conda/conda-build/pull/1418

**Comment by clonker** [comment] 2016-10-04 13:08
This is a slightly different issue but within the same context, so I am commenting here:

For us the conda build was failing in exactly the same step (due to changes in 39503ec and a difference in the way how utils.relative and stdlib-relative handles paths):
```
Traceback (most recent call last):
  File "/home/mho/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 782, in build
    croot=config.croot)
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 414, in post_build
    mk_relative(m, f, prefix)
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 381, in mk_relative
    mk_relative_linux(f, prefix=prefix, rpaths=m.get_value('build/rpaths', ['lib']))
  File "/home/mho/miniconda2/lib/python2.7/site-packages/conda_build/post.py", line 354, in mk_relative_linux
    rel_ours, rel_stdlib, f, rpath)
AssertionError: utils.relative ./readdy_plugins and relpath readdy_plugins disagree for lib/libReaDDy.so, lib/readdy_plugins/
```
A temporary fix consisted out of moving the 'readdy_plugins'-directory out of the lib-directory.

**Comment by mingwandroid** [comment] 2016-10-04 13:20
This is interesting, is your recipe public?

**Comment by clonker** [comment] 2016-10-04 13:42
Yes, you can find the recipe [here](https://github.com/readdy/readdy/tree/master/tools/conda-recipe).

I think the issue is simply that there are libraries within 'lib/' and 'lib/readdy_plugins/', since then (for a library in 'lib/'), utils.relative will report './readdy_plugins' and os.path.relpath will report 'readdy_plugins'.

**Comment by jakirkham** [comment] 2018-01-16 00:02
I think this was fixed with PR ( https://github.com/conda/conda-build/pull/1418 ), correct?

**Comment by jakirkham** [comment] 2018-11-04 05:36
Should be closed I think.

**Comment by clonker** [comment] 2018-11-06 08:31
Hi, sorry for not responding to your first comment! I worked around the problem at the time and then forgot about it. So after testing I can confirm: The problem I had encountered is fixed with a recent version of conda-build.

**Comment by msarahan** [comment] 2018-11-07 12:49
Thanks, closing

**Closed by msarahan** 2018-11-07 12:49 UTC

**Comment by dpryan79** [comment] 2019-04-10 19:08
I just ran into this same issue in a recipe on bioconda: https://github.com/bioconda/bioconda-recipes/pull/14233

This seems to be packaging statically linked executables.
