### ISSUE TITLE
AssertionError during dependency resolution

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#404] opened 2015-05-12 16:00 UTC
I've run into an `AssertionError` while using `conda build`.  Using my github repo and binstar channel, it's easy to reproduce on linux.  Use the steps below.

(It's worth noting that this recipe was building just fine until I started adding explicit dependency requirements to my `meta.yaml` files.)

```
$ # Use my binstar channel
$ cat > ~/.condarc
channels:
 - stuarteberg
 - defaults

$ # Clone my recipe repo
$ git clone https://github.com/ilastik/ilastik-build-conda
$ cd ilastik-build-conda

$ # Build this meta-package (which depends on another meta-package)
$ conda build ilastik-deps-carving
Removing old build directory
Removing old work directory
BUILD START: ilastik-deps-carving-1.1-0
Fetching package metadata: ........
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 118, in main
    args_func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 288, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 344, in build
    override_channels=override_channels)
  File "/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 265, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/miniconda/lib/python2.7/site-packages/conda/plan.py", line 401, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 749, in solve
    minimal_hint=minimal_hint)
  File "/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: vigra-1.10-a590b5b.tar.bz2 MatchSpec(u'boost ==1.55')
```

**Comment by asmeurer** [comment] 2015-05-12 19:36
This is a [known issue](https://github.com/conda/conda/issues/918). If you add an explicit specification for a dependency, you must also specify all the recursive dependencies. Closing as a duplicate of the conda issue.

**Closed by asmeurer** 2015-05-12 19:36 UTC

**Comment by stuarteberg** [comment] 2015-05-12 19:41
Thanks for the explanation.  So, just to make sure I understand: "explicit specification" means supplying an exact build version and also the build string, for every dependency, in all `meta.yaml` files?  I can do that.

**Comment by asmeurer** [comment] 2015-05-12 19:52
Yes, "exact" means the version and the build string. I don't remember if you need all dependencies or just the ones of the exact packages. Basically any package that shows up in the AssertionError must be specified in the meta.yaml.
