### ISSUE TITLE
conda build -t captures activate.d scripts from root env

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#3626] opened 2019-07-23 16:50 UTC
### Actual Behavior

conda build -t ~/Downloads/some-python-package.tar.bz2

ends up activating all kinds of compilers

### Expected Behavior

Only the test env created for the package should be activated

### Steps to Reproduce

I ran into this on a mac, but I'd be surprised if it were mac-specific.  The package I ran was conda-package-handling-1.3.11-py37_0.tar.bz2, but I don't think that matters much.

##### `Output of conda info`

```
     active environment : base
    active env location : /Users/msarahan/anaconda3
            shell level : 2
       user config file : /Users/msarahan/.condarc
 populated config files : /Users/msarahan/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /Users/msarahan/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/msarahan/anaconda3/pkgs
                          /Users/msarahan/.conda/pkgs
       envs directories : /Users/msarahan/anaconda3/envs
                          /Users/msarahan/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/18.0.0 OSX/10.14
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment] 2019-07-23 18:53
I can reproduce this issue on linux-64 using conda 3.18.9

**Comment by jjhelmus** [comment] 2019-07-23 22:20
I looked into this and the failing tests seem to be caused by the statsmodels 0.10.0 package having a `setup.cfg` file in the package root which pytest finds by walking up the directory tree from the `conda-bld` directory.  Passing `--croot /another/path` to conda-build will allow the tests to pass with the 0.10.0 package or statsmodels can be upgraded to 0.10.1 which does not have the file.

After more digging, I noticed that the compiler activation was sandwiched between deactivations. The compilers are not activated in the tests environment but in the process of creating and activating the test environment the deactivation scripts from the base are called.

@msarahan I'm going to close this as I suspect you were seeing similar issues, feel free to re-open if you were seeing something different.

**Closed by jjhelmus** 2019-07-23 22:20 UTC
