### ISSUE TITLE
Conda build tutorial failed on Win7

### ISSUE THREAD

**Issue by kc-hyperaxes** [conda/conda-build#500] opened 2015-07-22 23:44 UTC
Traceback below...

Current conda install:

             platform : win-64
        conda version : 3.15.0
  conda-build version : 1.15.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : C:\Users\Gene\Anaconda  (writable)
  default environment : C:\Users\Gene\Anaconda
     envs directories : C:\Users\Gene\Anaconda\envs
        package cache : C:\Users\Gene\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Traceback (most recent call last):
  File "C:\Users\Gene\Anaconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\main_build.py", line 400, in args_func
    args.func(args, p)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\pypi.py", line 739, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\pypi.py", line 786, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Users\Gene\Anaconda\lib\site-packages\conda_build\source.py", line 235, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "C:\Users\Gene\Anaconda\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Gene\Anaconda\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\Gene\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\Gene\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 740] The requested operation requires elevation

**Comment by remram44** [comment] 2016-01-02 18:15
Duplicate of #119, should be fixed by the new version of patch.

**Comment by msarahan** [comment] 2016-01-02 18:23
Thanks @remram44 closing

**Closed by msarahan** 2016-01-02 18:23 UTC
