### ISSUE TITLE
Problem: conda-build 3.0.6 failed to build package due to missing RUN requirements

### ISSUE THREAD

**Issue by argltuc** [conda/conda-build#2220] opened 2017-07-20 12:32 UTC
While building a meta package without any build requirements, conda build failed due to missing RUN requirements. This seems a new behavior since conda build 2.x. Does conda build 3.0.6 checks all requirements, even if they are not necessary in any way for the build process?
Is it possible to skip this specific requirement checking?

**Comment by msarahan** [comment] 2017-07-20 13:20
Sorry, this is a duplicate of #2217.  There was a change in #2218 that could present you with a workaround.  If you pass --no-test, this requirement check will not occur.

**Closed by msarahan** 2017-07-20 13:20 UTC

**Comment by msarahan** [comment] 2017-07-20 13:21
PS: forgot to mention that the fix in #2218 is present in 3.0.7 which has been tagged and should be available shortly if not already.
