### ISSUE TITLE
Invalid use of JSONDecodeError with Python 2.7

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#3309] opened 2018-12-12 16:44 UTC
7aa44a765 introduced `json.decoder.JSONDecodeError` which does not exist in Python 2.7.
The following patch should fix that:
```patch
From d6ed0f0a2ee3492dafad7790ccc161e4dc54deec Mon Sep 17 00:00:00 2001
From: Pavol Juhas <pavol.juhas@gmail.com>
Date: Wed, 12 Dec 2018 11:41:57 -0500
Subject: [PATCH] Avoid use of undefined JSONDecodeError

Python 2.7 does not have `json.decoder.JSONDecodeError`.
Solution: replace with mock JSONDecodeError.
---
 conda_build/index.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/conda_build/index.py b/conda_build/index.py
index 9f1ccc8c..363302bb 100644
--- a/conda_build/index.py
+++ b/conda_build/index.py
@@ -169,7 +169,7 @@ def _download_channeldata(channel_url):
         try:
             with open(tf) as f:
                 data = json.load(f)
-        except json.decoder.JSONDecodeError:
+        except JSONDecodeError:
             data = {}
     return data
 
@@ -270,7 +270,7 @@ def get_build_index(subdir, bldpkgs_dir, output_folder=None, clear_cache=False,
                             with open(channeldata_file, "r+") as f:
                                 channel_data[channel.name] = json.load(f)
                             break
-                        except (IOError, json.decoder.JSONDecodeError):
+                        except (IOError, JSONDecodeError):
                             time.sleep(0.2)
                             retry += 1
                 else:
-- 
2.19.2

```

**Comment by msarahan** [comment] 2018-12-12 16:58
duplicate of #3307, closing

**Closed by msarahan** 2018-12-12 16:58 UTC
