### ISSUE TITLE
conda-build caches source tree too aggressively

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#1133] opened 2016-07-21 12:30 UTC
Let's say I have the following recipe for easily testing changes locally:
```
package:
  name: mypkg
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  path: ../

test:
  commands:
    - do_something
```

Unfortunately, if I built this recipe once and GIT_DESCRIBE_NUMBER doesn't change, whatever later changes I make in the source tree, conda-build will not pick them up and re-use the old source tree. I then have to manually set a bogus build number each time I change something in the source tree.

This also seems to be a regression, as I didn't encounter this before.

**Comment by msarahan** [comment] 2016-07-21 14:02
Yeah... Arguably, we should never cache relative paths.  I'll fix that.

**Comment by msarahan** [comment] 2016-07-22 03:27
I've spent some time looking into this, and have not been able to figure it out.  Recipes with source/path should not be caching anything at all:

```
    elif 'path' in meta:
        if verbose:
            print("Copying %s to %s" % (abspath(join(recipe_dir, meta.get('path'))), WORK_DIR))
        copytree(abspath(join(recipe_dir, meta.get('path'))), WORK_DIR)
```

https://github.com/conda/conda-build/blob/master/conda_build/source.py#L403-L406

Are you sure that you're using source/path, and not git_url?  Do you have a sample recipe I can reproduce with?  My efforts to create one have not helped me recreate this issue.  Still, I think that this is related to the long-running issues we've had with our test suite on CI with stale ```__conda_version__.txt``` files hanging around, and I'd very much like to get this sorted out.

Note that this is not a problem after #1103, but that might be a little way off.

**Comment by pitrou** [comment] 2016-07-22 09:18
This is the recipe I was building: https://github.com/numba/numba/blob/master/buildscripts/condarecipe.local/meta.yaml

**Comment by msarahan** [comment] 2016-07-23 03:57
Fixed in #1140, new tag coming soon.  Closing this issue for now - will gladly reopen if issues recur.

**Closed by msarahan** 2016-07-23 03:57 UTC

**Comment by dhirschfeld** [comment] 2017-08-30 07:22
Just posting here, since I've moved to 3 my local src `../` builds often use a stale cache.

Wondering if anything has changed / anyone else has noticed?

```
conda-build               3.0.14           py36hbc735f7_0
```

**Comment by msarahan** [comment] 2017-08-30 13:56
are you using path or git_url for your local src builds?

The only recent change I know of is the addition of hashes to filenames in the source cache, added in 3.0.13.  I don't know why that would be affecting you - it should only affect ``url`` type sources.

**Comment by dhirschfeld** [comment] 2017-08-30 23:50
I'm using `  git_url: ../`, but also building with `--old-build-string`

**Comment by msarahan** [comment] 2017-08-31 00:00
Can you come up with a simple procedure that reproduces the problem?  Honestly, I can't completely support --old-build-string.  It's infeasible to test absolutely everything with that setting, and I don't trust things that are not tested.  If you don't like the new hashes, you might want to stick with the 2.1.x series.  At the very least, I need to ask for your help in writing test cases on the 3.0.x series if you insist on that setting.

**Comment by dhirschfeld** [comment] 2017-08-31 00:39
Happy to try and come up with a test case.

It's fair to say that I'm not yet sold on the hashes - it seems to be solving a problem we weren't having so I'm reluctant to pay the cost (of inscrutable and ugly filenames) if we don't have to.  I likely just have to educate myself a bit more about it and get comfortable with it.

It would seem to me though that if you have the ability to explicitly specify the exact build string manually then `--old-build-string` should be able to Just Work by taking the same code path? Or, put another way if `--old-build-string` is broken then likely explicitly providing the build string is also similarly broken. If I can come up with  a test case I can try to check that out too...

**Comment by dhirschfeld** [comment] 2017-08-31 00:51
NB: While it is documented under [build-packages/variants](https://conda.io/docs/user-guide/tasks/build-packages/variants.html?highlight=hash#differentiating-packages-built-with-different-variants) it seems that [package naming conventions](https://github.com/conda/conda-docs/blob/fe313e9ab6c7f9a31b02481ea8fc589716b01382/docs/source/user-guide/tasks/build-packages/package-naming-conv.rst) is a bit out of date:

![](https://raw.githubusercontent.com/conda/conda-docs/fe313e9ab6c7f9a31b02481ea8fc589716b01382/docs/source/img/conda_names.png)

**Comment by msarahan** [comment] 2017-08-31 01:30
No, that convention is still perfectly valid.  The build string now additionally includes the hash.  ``--old-build-string`` does nominally work, and there are tests for it, but I'm not going to double my test time by running the entire suite with and without that flag.  If you have better ideas of how to generalize build string information to arbitrary packages, I'm happy to discuss it.  I found an inscrutable hash more palatable than a scrutable, insanely long string with ambiguous abbreviations.

```py27np111hdf5110mkl2018qt56vc9```

I would like to provide tools one day to query the internal contents of these hash-named packages, so that you can do things like "show me all the packages built with qt 5.6."  It's certainly possible, but it will take time.

I also would be surprised if ``--old-build-string`` ends up being the thing breaking you here, but in the absence of anything else, it's easy to point at.  By the way, if you customize your build string at all (any entry in meta.yaml for build/string), then the hashes will not be added.  That changed around 3.0.11 or 3.0.12, IIRC.

**Comment by dhirschfeld** [comment] 2017-08-31 02:08
> If you have better ideas of how to generalize build string...

No, no better ideas - as mentioned I probably just need to get my head around it. We've got an established build process so I'll have to check it doesn't break any of our assumptions. I don't think it will, but haven't had time to check just yet so have been using the `-old-build-string` to keep the existing behaviour... for now.
