### ISSUE TITLE
Exception: info/files for `site-packages/[PACKAGE_NAME]-[VERSION].dist-info/Icon\r' not in info/files`

### ISSUE THREAD

**Issue by jolespin** [conda/conda-build#4373] opened 2022-02-01 04:26 UTC
### Actual Behavior

```
Packaging soothsayer_utils
INFO:conda_build.build:Packaging soothsayer_utils
INFO conda_build.build:build(2214): Packaging soothsayer_utils
Packaging soothsayer_utils-2022.01.19-py_0
INFO:conda_build.build:Packaging soothsayer_utils-2022.01.19-py_0
INFO conda_build.build:bundle_conda(1454): Packaging soothsayer_utils-2022.01.19-py_0
number of files: 11
Fixing permissions
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.09 seconds
'site-packages/soothsayer_utils-2022.1.19.dist-info/Icon' not in tarball
'site-packages/soothsayer_utils-2022.1.19.dist-info/Icon\r' not in info/files
Traceback (most recent call last):
  File "/Users/jespinoz/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 3008, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 2291, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 1619, in bundle_conda
    tarcheck.check_all(tmp_path, metadata.config)
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/tarcheck.py", line 89, in check_all
    x.info_files()
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/tarcheck.py", line 53, in info_files
    raise Exception('info/files')
Exception: info/files
```

### Expected Behavior

I've used a `global-exclude Icon*` in my `MANIFEST.in` file but for some reason `conda build` is still looking for `Icon` files which AFAIK are extra files added by Google Drive. These files are not supposed to be packaged up and I can confirm they are not in the tar.gz on GitHub.  I've even tried including the Icon files in the tar.gz but still got the error.

Here's my `MANIFEST.in` file: 

```
graft soothsayer_utils
include setup.py
include LICENSE.txt
include README.md
global-exclude *.py[cod]
global-exclude Icon*
global-exclude .DS_Store
```

### Steps to Reproduce

`conda build .`

##### `Output of conda info`

```
(base) jespinoz@jespinozlt2-osx soothsayer_utils % conda info

     active environment : base
    active env location : /Users/jespinoz/anaconda3
            shell level : 1
       user config file : /Users/jespinoz/.condarc
 populated config files : /Users/jespinoz/.condarc
          conda version : 4.11.0
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jespinoz/anaconda3  (writable)
      conda av data dir : /Users/jespinoz/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jespinoz/anaconda3/pkgs
                          /Users/jespinoz/.conda/pkgs
       envs directories : /Users/jespinoz/anaconda3/envs
                          /Users/jespinoz/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.24.0 CPython/3.8.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 3456:20
             netrc file : None
           offline mode : False
```

<details>
  <summary>Here's the complete log: </summary>
  
  ```
(base) jespinoz@jespinozlt2-osx soothsayer_utils % conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for soothsayer_utils
INFO:conda_build.metadata:Attempting to finalize metadata for soothsayer_utils
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['soothsayer_utils-2022.01.19-py_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


The following NEW packages will be INSTALLED:

    bzip2:           1.0.8-h0d85af4_4          conda-forge
    ca-certificates: 2021.10.8-h033912b_0      conda-forge
    libffi:          3.4.2-h0d85af4_5          conda-forge
    libzlib:         1.2.11-h9173be1_1013      conda-forge
    ncurses:         6.3-he49afe7_0            conda-forge
    openssl:         3.0.0-h0d85af4_2          conda-forge
    pip:             22.0.2-pyhd8ed1ab_0       conda-forge
    python:          3.10.2-hea1dfa3_2_cpython conda-forge
    python_abi:      3.10-2_cp310              conda-forge
    readline:        8.1-h05e3726_0            conda-forge
    setuptools:      60.6.0-py310h2ec42d9_0    conda-forge
    sqlite:          3.37.0-h23a322b_0         conda-forge
    tk:              8.6.11-h5dbffcc_1         conda-forge
    tzdata:          2021e-he74cb21_0          conda-forge
    wheel:           0.37.1-pyhd8ed1ab_0       conda-forge
    xz:              5.2.5-haf1e3a3_1          conda-forge
    zlib:            1.2.11-h9173be1_1013      conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /Users/jespinoz/anaconda3/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/jespinoz/anaconda3/conda-bld/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /Users/jespinoz/anaconda3/conda-bld/src_cache
No hash (md5, sha1, sha256) provided for soothsayer_utils-2022.1.19.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for soothsayer_utils-2022.1.19.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING conda_build.source:download_to_cache(61): No hash (md5, sha1, sha256) provided for soothsayer_utils-2022.1.19.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
Found source in cache: soothsayer_utils-2022.1.19.tar.gz
INFO:conda_build.source:Found source in cache: soothsayer_utils-2022.1.19.tar.gz
INFO conda_build.source:download_to_cache(66): Found source in cache: soothsayer_utils-2022.1.19.tar.gz
Extracting download
source tree in: /Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/work
export PREFIX=/Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export SRC_DIR=/Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/work
Using pip 22.0.2 from $PREFIX/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-1eptgxgb
Created temporary directory: /private/tmp/pip-req-tracker-11pj__8d
Initialized build tracking at /private/tmp/pip-req-tracker-11pj__8d
Created build tracker: /private/tmp/pip-req-tracker-11pj__8d
Entered build tracker: /private/tmp/pip-req-tracker-11pj__8d
Created temporary directory: /private/tmp/pip-install-bpfyixb_
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/private/tmp/pip-req-tracker-11pj__8d'
  Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
  Created temporary directory: /private/tmp/pip-pip-egg-info-xtixyq2s
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  /Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.10/site-packages/setuptools/dist.py:501: UserWarning: Normalizing '2022.01.19' to '2022.1.19'
    warnings.warn(tmpl.format(**locals()))
  running egg_info
  writing /private/tmp/pip-pip-egg-info-xtixyq2s/soothsayer_utils.egg-info/PKG-INFO
  writing dependency_links to /private/tmp/pip-pip-egg-info-xtixyq2s/soothsayer_utils.egg-info/dependency_links.txt
  writing requirements to /private/tmp/pip-pip-egg-info-xtixyq2s/soothsayer_utils.egg-info/requires.txt
  writing top-level names to /private/tmp/pip-pip-egg-info-xtixyq2s/soothsayer_utils.egg-info/top_level.txt
  reading manifest file '/private/tmp/pip-pip-egg-info-xtixyq2s/soothsayer_utils.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  Preparing metadata (setup.py): finished with status 'done'
  Source in $SRC_DIR has version 2022.1.19, which satisfies requirement soothsayer-utils==2022.1.19 from file://$SRC_DIR
  Removed soothsayer-utils==2022.1.19 from file://$SRC_DIR from build tracker '/private/tmp/pip-req-tracker-11pj__8d'
Created temporary directory: /private/tmp/pip-unpack-ka2nvft3
Building wheels for collected packages: soothsayer-utils
  Created temporary directory: /private/tmp/pip-wheel-76_5dgv3
  Building wheel for soothsayer-utils (setup.py): started
  Destination directory: /private/tmp/pip-wheel-76_5dgv3
  Running command python setup.py bdist_wheel
  /Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.10/site-packages/setuptools/dist.py:501: UserWarning: Normalizing '2022.01.19' to '2022.1.19'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_py
  warning: build_py: byte-compiling is disabled, skipping.

  /Users/jespinoz/anaconda3/conda-bld/soothsayer_utils_1643688880113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  running install_lib
  copying build/lib/soothsayer_utils/soothsayer_utils.py -> build/bdist.macosx-10.9-x86_64/wheel/soothsayer_utils
  copying build/lib/soothsayer_utils/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/soothsayer_utils
  warning: install_lib: byte-compiling is disabled, skipping.

  running install_egg_info
  running egg_info
  writing soothsayer_utils.egg-info/PKG-INFO
  writing dependency_links to soothsayer_utils.egg-info/dependency_links.txt
  writing requirements to soothsayer_utils.egg-info/requires.txt
  writing top-level names to soothsayer_utils.egg-info/top_level.txt
  reading manifest file 'soothsayer_utils.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  running install_scripts
  adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
  creating build/bdist.macosx-10.9-x86_64/wheel/soothsayer_utils-2022.1.19.dist-info/WHEEL
  creating '/private/tmp/pip-wheel-76_5dgv3/soothsayer_utils-2022.1.19-py3-none-any.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
  adding 'soothsayer_utils/__init__.py'
  adding 'soothsayer_utils/soothsayer_utils.py'
  adding 'soothsayer_utils-2022.1.19.dist-info/.DS_Store'
  adding 'soothsayer_utils-2022.1.19.dist-info/Icon
  '
  adding 'soothsayer_utils-2022.1.19.dist-info/LICENSE.txt'
  adding 'soothsayer_utils-2022.1.19.dist-info/METADATA'
  adding 'soothsayer_utils-2022.1.19.dist-info/WHEEL'
  adding 'soothsayer_utils-2022.1.19.dist-info/top_level.txt'
  adding 'soothsayer_utils-2022.1.19.dist-info/RECORD'
  removing build/bdist.macosx-10.9-x86_64/wheel
  Building wheel for soothsayer-utils (setup.py): finished with status 'done'
  Created wheel for soothsayer-utils: filename=soothsayer_utils-2022.1.19-py3-none-any.whl size=25151 sha256=cdef8664fdc28b54d8dc4a1ab9ea5b6231f1a7a970d277c71d4326c151779067
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-1eptgxgb/wheels/85/91/cb/7a6f0061ec2284ef320289124a6f023d1116ae53b8a60948f3
Successfully built soothsayer-utils
Installing collected packages: soothsayer-utils

Successfully installed soothsayer-utils-2022.1.19
Removed build tracker: '/private/tmp/pip-req-tracker-11pj__8d'

Resource usage statistics from building soothsayer_utils:
   Process count: 4
   CPU time: Sys=0:00:00.4, User=0:00:00.9
   Memory: 81.0M
   Disk usage: 544B
   Time elapsed: 0:00:10.3


Packaging soothsayer_utils
INFO:conda_build.build:Packaging soothsayer_utils
INFO conda_build.build:build(2214): Packaging soothsayer_utils
Packaging soothsayer_utils-2022.01.19-py_0
INFO:conda_build.build:Packaging soothsayer_utils-2022.01.19-py_0
INFO conda_build.build:bundle_conda(1454): Packaging soothsayer_utils-2022.01.19-py_0
number of files: 11
Fixing permissions
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.09 seconds
'site-packages/soothsayer_utils-2022.1.19.dist-info/Icon' not in tarball
'site-packages/soothsayer_utils-2022.1.19.dist-info/Icon\r' not in info/files
Traceback (most recent call last):
  File "/Users/jespinoz/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 3008, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 2291, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 1619, in bundle_conda
    tarcheck.check_all(tmp_path, metadata.config)
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/tarcheck.py", line 89, in check_all
    x.info_files()
  File "/Users/jespinoz/anaconda3/lib/python3.8/site-packages/conda_build/tarcheck.py", line 53, in info_files
    raise Exception('info/files')
Exception: info/files
  ```
</details>

<details>
<summary> Here's the `meta.yaml` </summary>

```
(base) jespinoz@jespinozlt2-osx soothsayer_utils % cat meta.yaml
{% set name = "soothsayer_utils" %}
{% set version = "2022.01.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://github.com/jolespin/soothsayer_utils/releases/download/v2022.01.19/soothsayer_utils-2022.1.19.tar.gz

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pandas >=0.24.2
    - tqdm
    - bz2file
    - tzlocal
    - pathlib2
    - requests
    - numpy >=1.11

about:
  home: https://github.com/jolespin/soothsayer_utils
  license: BSD-3
  license_family: BSD
  summary: 'Utility functions for Soothsayer'
  description: 'Utility functions for Soothsayer'
```

</details>

<details>
<summary> Here's my `build.sh` script </summary>

```
$PYTHON -m pip install . --ignore-installed --no-deps -vv
rm -rf ${PREFIX}/info/Icon
rm -rf ${PREFIX}/info/Icon*
```
</details>

I can confirm that the `Icon` files do not exist in my [soothsayer_utils-2022.1.19.tar.gz](https://github.com/jolespin/soothsayer_utils/releases/download/v2022.01.19/soothsayer_utils-2022.1.19.tar.gz) file:

```
(base) jespinoz@x86_64-apple-darwin13 Downloads % tree soothsayer_utils-2022.1.19
soothsayer_utils-2022.1.19
├── LICENSE.txt
├── MANIFEST.in
├── PKG-INFO
├── README.md
├── setup.cfg
├── setup.py
├── soothsayer_utils
│   ├── __init__.py
│   └── soothsayer_utils.py
└── soothsayer_utils.egg-info
    ├── PKG-INFO
    ├── SOURCES.txt
    ├── dependency_links.txt
    ├── requires.txt
    └── top_level.txt

2 directories, 13 files
```

**Comment by jezdez** [comment] 2022-02-03 13:55
@jolespin Could you please add the section what the expected behavior is? I'm not sure I can follow what you're trying to do.

**Comment by jolespin** [comment] 2022-02-03 20:35
Apologies, I've updated that setcion.

**Comment by kenodegard** [comment] 2022-03-04 23:48
@jolespin Looks like you got this resolved on [StackOverflow](https://stackoverflow.com/questions/70934699/how-to-fix-error-when-building-conda-package-related-to-icon-file) so I'll go ahead and close this out.

**Closed by kenodegard** 2022-03-04 23:48 UTC
Labels: type::support, source::community, pending::support
