### ISSUE TITLE
Python 3.4 build failures

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#895] opened 2016-04-26 00:13 UTC
Running into a strange issue in a number of cases where conda-build 1.20.1 cannot build Python 3.4 64-bit packages. This problem does not occur in conda-build 1.20.0. See related issue ( https://github.com/conda-forge/staged-recipes/issues/448 ) and use cases documented within.

cc @msarahan @patricksnape

**Comment by msarahan** [comment] 2016-05-04 20:04
These seem to be caused by MSYS2 path conversion, plus extra CL environment variable settings set by the win 7 SDK's setenv.cmd:

    CL=/AI C:\Program Files\...

becomes
    
    CL=C:/root/of/msys2/AI C:\Program Files\...

@mingwandroid has been very helpful in debugging this.  We investigating a fix, which might include changing / to - in the CL variable, since MS tools recognize arguments like that also.

Alternatives:
  - set MSYS2_ARG_CONV_EXCL=“/AL;/OUT;%MSYS2_ARG_CONV_EXCL%" - MSYS2 should ignore paths starting with patterns here.  Semicolon delimited.
  - set MSYS2_ENV_CONV_EXCL=“CL" - MSYS2 should ignore path conversion in the CL environment variable

**Comment by msarahan** [comment] 2016-05-04 20:05
This will require more test coverage - ideally, building some small project that uses a configure script.  If anyone has suggestions, I'd like to hear them.

**Comment by mingwandroid** [comment] 2016-05-04 20:07
Path conversion is a fact of MSYS2 life, arguments that 'look like' POSIX paths get turned into their Windows equivalent when calling Windows programs from POSIX programs.

The same happens for env. vars and can be excluded with `MSYS2_ENV_CONV_EXCL`.

It's better than Windows programs getting POSIX paths and not being able to do anything with them.

**Comment by mingwandroid** [comment] 2016-05-04 20:26
I should clarify, in this case because configure interpolates the CL variable into the command line args, `MSYS2_ENV_CONV_EXCL` won't be useful for this one.

**Comment by msarahan** [comment] 2016-05-10 03:00
I think this is fixed between #900 and #933 - I'm going to close it for now, but please comment here or reopen it if any further issues like this crop up.  I don't think this will be truly, reliably fixed until we have conda-build activating environments rather than changing PATH directly.

**Closed by msarahan** 2016-05-10 03:00 UTC
