### ISSUE TITLE
Issues with --prefix-length and other conda commands

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda-build#3824] opened 2019-12-08 17:57 UTC
My primary development machine is a Linux laptop with an encrypted home directory.  As such, I always run into 

```
conda.CondaError: Unable to create prefix directory '/home/hugo/miniconda3/conda-bld/skeleton_1575827532030/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla'.
````

I can fix this when calling `conda build` by passing `--prefix-length`, but not into other commands that do not support the flag (like `conda skeleton`). 

What's the recommended work around for this?  Would there be support for a PR adding `prefix-length` to `.condarc`?

Thanks

**Comment by msarahan** [comment] 2019-12-08 22:18
Duplicate of https://github.com/conda/conda-build/issues/1331. Please see discussion in that issue.

**Closed by msarahan** 2019-12-08 22:18 UTC
