### ISSUE TITLE
--no-include-recipe skips tests

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#2588] opened 2017-12-18 20:25 UTC
Running conda build with the `--no-include-recipe` argument skips any tests present in the recipe.

For example:

``` yaml
package:
  name: example
  version: "1.0.0"

test:
  commands:
    - exit 1
```

```
$ conda build -V
conda-build 3.1.6
$ conda build .
Attempting to finalize metadata for example
INFO:conda_build.metadata:Attempting to finalize metadata for example
BUILD START: ['example-1.0.0-0.tar.bz2']
source tree in: /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work
Packaging example
INFO:conda_build.build:Packaging example
Packaging example-1.0.0-0
INFO:conda_build.build:Packaging example-1.0.0-0
No files or script found for output example
WARNING:conda_build.build:No files or script found for output example
number of files: 0
Fixing permissions
Fixing permissions
updating: example-1.0.0-0.tar.bz2
Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
TEST START: /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2
Renaming work directory,  /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work  to  /home/jhelmus/anaconda3/conda-bld/example_1513628615828/work_moved_example-1.0.0-0_linux-64

The following NEW packages will be INSTALLED:

    example: 1.0.0-0 local

+ exit 1
Tests failed for example-1.0.0-0.tar.bz2 - moving package to /home/jhelmus/anaconda3/conda-bld/broken
WARNING:conda_build.build:Tests failed for example-1.0.0-0.tar.bz2 - moving package to /home/jhelmus/anaconda3/conda-bld/broken
removing: example-1.0.0-0.tar.bz2
TESTS FAILED: example-1.0.0-0.tar.bz2
```
```
 example-1.0.0-0.tar.bz2
~/sandbox/bug$ conda build --no-include-recipe .
Attempting to finalize metadata for example
INFO:conda_build.metadata:Attempting to finalize metadata for example
BUILD START: ['example-1.0.0-0.tar.bz2']
source tree in: /home/jhelmus/anaconda3/conda-bld/example_1513628647377/work
Packaging example
INFO:conda_build.build:Packaging example
Packaging example-1.0.0-0
INFO:conda_build.build:Packaging example-1.0.0-0
No files or script found for output example
WARNING:conda_build.build:No files or script found for output example
number of files: 0
Fixing permissions
Fixing permissions
updating: example-1.0.0-0.tar.bz2
Error extracting info/recipe/meta.yaml in /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
WARNING:conda_build.index:Error extracting info/recipe/meta.yaml in /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/home/jhelmus/anaconda3/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/linux-64 to make package installable with dependencies
Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/jhelmus/anaconda3/conda-bld/noarch to make package installable with dependencies
Nothing to test for: /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/jhelmus/anaconda3/conda-bld/linux-64/example-1.0.0-0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []



####################################################################################
Source and build intermediates have been left in /home/jhelmus/anaconda3/conda-bld.
There are currently 2 accumulated.
To remove them, you can run the ```conda build purge``` command
````

**Comment by msarahan** [comment] 2017-12-18 20:26
Duplicate of #2457 I think.  Thanks for the reminder.  I'll work on this for the next release.

**Comment by jjhelmus** [comment] 2017-12-18 20:29
I think #2457 is a bit different.  In that issue `--no-include-recipe` breaks the build, here it incorrectly fixes the build.  Likely the same underlying cause, the testing phase requires that some portions of the recipe be present.

**Closed** 2017-12-19 17:55 UTC
