### ISSUE TITLE
Build problems with 3.9.1 

### ISSUE THREAD

**Issue by skrah** [conda/conda-build#2847] opened 2018-04-26 20:43 UTC
Hello,

Version `3.9.1` breaks the `libndtypes` build, here's an example:

   https://travis-ci.org/plures/ndtypes/jobs/371683588#L2160

I'm not sure if it is a configuration issue on the `libndtypes` side.  For example, is `libndtypes-0.2.0dev3-py36_98_g0c154fc` still a valid name?  Apparently the dependency checker searches for `0.2.0dev.3` (note the dot between `dev` and `3`).

I "solved" this by downgrading conda-build to `3.3.0`:

   https://travis-ci.org/plures/ndtypes/jobs/371746955

**Comment by msarahan** [comment] 2018-04-26 20:45
I think this is a duplicate of #2846 - please see that for discussion.

**Closed by msarahan** 2018-04-26 20:45 UTC
