### ISSUE TITLE
Empty GIT_DESCRIBE_TAG when building

### ISSUE THREAD

**Issue by RutgerK** [conda/conda-build#357] opened 2015-04-02 15:03 UTC
This might be related to #266, but im not sure, and the issue is still present in the latest version of conda-build (1.11.0).

I have a package for which the first part of the `meta.yaml` looks like:

```
package:
  name: package_name
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed')}}

source:
  git_url: git@gitlab:User/package_name.git
  git_tag: 1.0.3
```

The tag exists in the git repo, it is also correctly downloading the tarball. And when i look at what conda-build outputs in the console, it also correctly gets/sets the describe tag. But somehow it failed to retrieve this from the `environ` dict, resulting in a wrongly named package. The rest of the building process seems fine.
This is the output of the "git part" during the build process:

```
...
Removing old work directory
checkout: '1.0.3'
Cloning into 'C:\Miniconda\conda-bld\work'...
done.
Note: checking out '1.0.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at bc59578... update
==> git log -n1 <==

commit bc59578d64aca0a7f952f4b8336241af64e634d4
Author: User <email@email.com>
Date:   Thu Apr 2 14:04:31 2015 +0200

    update


==> git describe --tags --dirty <==

1.0.3


==> git status <==

HEAD detached at 1.0.3
nothing to commit, working directory clean


Package: package_name-failed-py33_0
...
```

The package is named with the default value, so apparently it cant find the key `GIT_DESCRIBE_TAG` in `environ`. It's hard to debug, is there anything i can do to get some extra information about whats going wrong?

Strangely, i have different projects on the same git-server, with an identical `meta.yalm` (except for the url and tag etc) which work fine. 

I have test it on my machine (Win 7 64bit, python 3.3, conda-build 1.11), and on a machine from my colleague (Win 8.1 64bit, python 3.4, conda-build 1.11), both with the same result.

**Comment by asmeurer** [comment] 2015-04-02 21:08
This is probably an instance of the bug where it picks up the git information from the previous build.

**Comment by kvdlande** [comment] 2015-04-03 07:21
It looks like the cause of the behaviour is the fact that the sources and setup.py are put in a subdirectory.
In order to share some eclipse project settings sources are placed in adirectory "src/".
In order to build my build.bat looks like:

cd src
"%PYTHON%" setup.py install
if errorlevel 1 exit 1
cd ..

**Comment by asmeurer** [comment] 2015-04-06 20:19
I don't see how that would affect the git environment variables. They are gathered before the bld.bat is run.

**Comment by cowlicks** [comment] 2015-05-12 19:19
[xref](https://github.com/ContinuumIO/dask/pull/203)

**Comment by sandhujasmine** [comment] 2016-02-28 06:28
I'm seeing the same issue on OSX. here's my conda-build version:
```
> conda list |grep conda-build
anaconda-build            0.12.0                   py27_0    defaults
conda-build               1.19.0                   py27_0    defaults
```

When I try the build, I don't get the git tag info in the package: `ps_datasci--np19py27_0`

```
> git describe --tags
v0.13.0-1-gf617599
(ps_pipeline)jsandhu@0204-jsandhu ~/ (conda-recipe)* > conda build conda.recipe/
Removing old build environment
Removing old work directory
BUILD START: ps_datasci--np19py27_0
Fetching package metadata: ..
```

I tried to put the following in build.sh but this doesn't work because I can't set the environment variable from inside a script.
```
export GIT_DESCRIBE_TAG=`git describe --tags | cut -d'-' -f 1`
```

**Comment by yoavram** [comment] 2016-03-03 07:03
I get a similar issue. `setup.py` ran by `conda-build` knows the package version, for example:
```
Copying curveball.egg-info to D:\Anaconda3\envs\_build\Lib\site-packages\curveball-0.2.3+3.g3e5d512.dirty-py3.4.egg-info
```
but `conda-build` doesn't, for example:
```
STOPPING BUILD BEFORE POST: curveball--py34_0
```

**Comment by yoavram** [comment] 2016-03-03 14:33
UPDATE:
I had to change in `meta.yml` in the `source` section from `path` to `git_url`, but didn't have to change the value `../`. 
That fixed the problem.
conda-build v 1.19.0

**Comment by msarahan** [comment] 2016-03-03 14:37
Thanks @yoavram this is the correct solution.  The reason for this change was that someone had a .git folder in a recipe that was not a git recipe (used path, not git_url).  This recipe failed to build because the person didn't have git installed.  Forcing people to use git url, even when it is a local relative path, makes the dependency on git more explicit.

**Comment by yoavram** [comment] 2016-03-03 14:41
I agree, but I have some vague memory that git_url didn't work locally in the past.
Perhaps it's a good idea that conda-build will warn if you use path and the version is empty? It can do something like: "Warning: version is empty, consider setting it in meta.yml or using git_url instead of path, see http://...."?

**Comment by msarahan** [comment] 2016-03-03 14:53
It should be doing that already - any template variable that is undefined should be presenting you with an error.  @stuarteberg did a ton of work on this area.  This work should be present in v.1.19.0.

@stuarteberg any idea where we should look to address this problem?

**Comment by yoavram** [comment] 2016-03-03 15:03
Also, Travis now fails after I changed from path to git_url (I verified and Travis uses conda-build 1.19.0 and conda 3.19.3):
```
Removing old work directory

Cloning into bare repository '/home/travis/miniconda2/conda-bld/git_cache/home_travis_build_yoavram_curveball'...

fatal: attempt to fetch/clone from a shallow repository

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

An unexpected error has occurred, please consider sending the

following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):

  File "/home/travis/miniconda2/bin/conda-build", line 5, in <module>

    sys.exit(main())

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 192, in main

    args_func(args, p)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 486, in args_func

    args.func(args, p)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 409, in execute

    include_recipe=args.include_recipe)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 411, in build

    source.provide(m.path, m.get_section('source'))

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/source.py", line 279, in provide

    git_source(meta, recipe_dir)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/conda_build/source.py", line 121, in git_source

    check_call(args + [git_url, cache_repo_arg],  cwd=recipe_dir)

  File "/home/travis/miniconda2/lib/python2.7/subprocess.py", line 540, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['/usr/bin/git', 'clone', '--mirror', u'../', u'/home/travis/miniconda2/conda-bld/git_cache/home_travis_build_yoavram_curveball']' returned non-zero exit status 128
```

**Comment by stuarteberg** [comment] 2016-03-03 15:14
There are multiple things to address here:

>When I try the build, I don't get the git tag info in the package: `ps_datasci--np19py27_0`

You are looking at the `BUILD START` console output.  At that time, the git repo hasn't even been checked out yet, so yeah, `GIT_DESCRIBE_TAG` is still empty.  If you wait until the end of the build, the 
correct package name should be shown.

>Perhaps it's a good idea that conda-build will warn if you use path and the version is empty?

If you use the following syntax, then you'll get a descriptive error if `GIT_DESCRIBE_TAG` is still undefined after the git source has been checked out:

```yaml
package:
  name: package_name
  version: {{ GIT_DESCRIBE_TAG }}
```

But the following syntax will not result in any explicit errors, because it ensures that `GIT_DESCRIBE_TAG` is always defined (with a default value if necessary).

```yaml
package:
  name: package_name
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default')}}
```

Therefore, I think the former is preferred.  IIRC, the docs are not clear on this point.  I'm sure a pull request to fix that would be appreciated.

>Also, Travis now fails after I changed from path to git_url

I'm afraid I don't know what's wrong there...

**Comment by yoavram** [comment] 2016-03-03 15:29
Thanks.

I think it's a problem to clone a shallow repo, and Travis creates a shallow repo from which conda-build tries to clone into its work folder.
You haven't seen this when building on travis?

**Comment by yoavram** [comment] 2016-03-03 16:05
Removing .git/shallow solves the problem.

**Comment by stuarteberg** [comment] 2016-03-03 17:00
>I think it's a problem to clone a shallow repo, and Travis creates a shallow repo from which conda-build tries to clone into its work folder.

Thanks for reporting this.

>Removing .git/shallow solves the problem.

I think the safer way to deal with this is to add `git fetch --unshallow` to your Travis setup, although I guess that would be slow for huge git repositories.

**Comment by stuarteberg** [comment] 2016-03-03 20:08
BTW, It seems to be the case that newer version of git actually do support cloning "shallow" repos, so I guess the Travis VM is using an old version of git.  FWIW, I saw the same issue on circle-ci, which uses git version 1.8.5.6.

**Comment by yoavram** [comment] 2016-03-03 20:16
That makes sense, because I didn't have that problem on my own PC. At any case, `git fetch --unshallow` does the trick. Thanks, I appreciate it!

**Comment by jakirkham** [comment] 2016-03-03 21:29
Some older versions of git don't have the `--unshallow` flag. Fortunately it is possible to install a new enough version of `git` with `conda` that has the flag. It is true that newer version of `git` allows cloning of shallow repos, which should is true of the newer `git` supplied with `conda`. It may require the repo to be updated to make it compatible with this feature.

**Comment by msarahan** [comment] 2016-05-07 01:21
I believe this issue is fixed in the 1.20.2beta release.  Please comment here, reopen this issue, or open a new issue if there are further questions.

**Closed by msarahan** 2016-05-07 01:21 UTC

**Comment by yoavram** [comment] 2016-06-01 06:55
Having problems again.TL;DR: I think conda-build copies rather than clone to the `work` folder, as there is no repo over there,

The recipe yaml has:
```yml
package:
  name: package_name
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../
```

Elaborate debugging session:

Running `git describe --tags --long HEAD` in the terminal gives a proper version (`v0.2.3-33-gaa1b37b`).

Running `conda build conda-recipe` gives `Error: Failed to render jinja template in D:\workspace\curveball_project\code\conda-recipe\meta.yaml:
'GIT_DESCRIBE_TAG' is undefined`.

I've hacked `conda_build/environ.py`. I found that `verify_git_repo` returns `False` from the `except CalledProcessError` block. I printed the exception and got:`CalledProcessError: Command '['git', 'log', '-n1', '--format=%H']' returned non-zero exit status 128`. Now I went in the terminal to `D:\Anaconda3\conda-bld\work` and ran `git log` and indeed I got the same status 128 error.

So it seems that conda-build copies the package folder but not as a git repo - is that correct?

I'd like to suggest that if `verify_git_repo` fails it will issue a warning that the work folder is not a repo - that would make debugging easier.

**Comment by stuarteberg** [comment] 2016-06-01 12:23
>it seems that conda-build copies the package folder but not as a git repo - is that correct?

That is not expected behavior in this case.  A plain copy is made if you specify a `path`:

```yaml
source:
  path: ../
```

but a proper git clone is made if you specify a `git_url`:

```yaml
source:
  git_url: ../
```

You should be able to see the local clone in `miniconda/conda-bld/git_cache/`.  Is it there?  What happens if you run `git log -n1 --format=%H` on that repo?  You may have to use the `GIT_DIR` environment variable, since it is a 'bare' repo.  For example, on my machine:

```
GIT_DIR=/miniconda/conda-bld/git_cache/Users_bergs_Documents_workspace_mypackage git log -n1 --format=%H
```

>Now I went in the terminal to `D:\Anaconda3\conda-bld\work` and ran `git log` and indeed I got the same status 128 error.

Is there any output on stderr when it returns the error?

**Comment by yoavram** [comment] 2016-06-01 12:33
I bypassed the problem for now with `version: {{ environ.get('GIT_DESCRIBE_TAG', 'default')}}` in the yml file.
Went back to `work` and now `git log` works... Same for `git_cache`. 
If I manage to reproduce the bug I'll get back to this thread..
