### ISSUE TITLE
Incorrect dependency resolution

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#407] opened 2015-05-13 19:14 UTC
Consider this tiny test case:

```
$ ls aaa/
build.sh  meta.yaml

$ cat aaa/meta.yaml 
package:
  name: aaa
  version: "0.1"
requirements:
  build:
    - gcc    4.8.2    2 # [linux]
    - python 2.7.9    2
  run:
    - libgcc 4.8.4 1

$ cat aaa/build.sh 
# If gcc is missing cloog, etc, this will fail.
echo "int main(){}" | ${PREFIX}/bin/gcc -xc -
```

When we build it, it fails:

```
$ conda build aaa
Removing old build directory
Removing old work directory
BUILD START: aaa-0.1-0
Fetching package metadata: ......
Solving package specifications: 
The following NEW packages will be INSTALLED:

    gcc:    4.8.2-2
    python: 2.7.9-2

Linking packages ...
[      COMPLETE      ]|#################################################################################################################| 100%
Removing old work directory
Copying /home/ilastik/ilastik-build-conda/aaa to /miniconda/conda-bld/work
Package: aaa-0.1-0
source tree in: /miniconda/conda-bld/work
+ echo 'int main(){}'
+ /miniconda/envs/_build/bin/gcc -xc -
/miniconda/envs/_build/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/cc1: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory
Command failed: /bin/bash -x -e /home/ilastik/ilastik-build-conda/aaa/build.sh
```

What happened?  In the output shown above, you can see that the dependencies of the `gcc` package **were not installed**, so the gcc binary didn't work at all.

Strangely, this problem seems to be caused by the `python` dependency.  If we comment out that line, the package builds.  Notice how, this time, the build will fetch gcc dependencies like `cloog`, `isl`, `gmp`, etc.  Now our silly little build script doesn't error out.

```
$ cat aaa/meta.yaml 
package:
  name: aaa
  version: "0.1"
requirements:
  build:
    - gcc    4.8.2    2 # [linux]
   #- python 2.7.9    2
  run:
    - libgcc 4.8.4 1

$ conda build aaa
Removing old build directory
Removing old work directory
BUILD START: aaa-0.1-0
Fetching package metadata: ......
Solving package specifications: .
The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0
    gcc:   4.8.2-2 
    gmp:   5.1.2-2 
    isl:   0.12.2-0
    mpc:   1.0.1-0 
    mpfr:  3.1.2-0 

Linking packages ...
[      COMPLETE      ]|#################################################################################################################| 100%
Removing old work directory
Copying /home/ilastik/ilastik-build-conda/aaa to /miniconda/conda-bld/work
Package: aaa-0.1-0
source tree in: /miniconda/conda-bld/work
+ echo 'int main(){}'
+ /miniconda/envs/_build/bin/gcc -xc -
number of files: 0
Fixing permissions
Fixing permissions
BUILD END: aaa-0.1-0
Nothing to test for: aaa-0.1-0
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /miniconda/conda-bld/linux-64/aaa-0.1-0.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes
```

BTW, version details:

```
$ conda --version
conda 3.12.0
$ conda build --version
conda-build 1.12.1
$ cat /etc/*release
CentOS release 5.11 (Final)
```

**Comment by asmeurer** [comment] 2015-05-13 19:27
This is an issue with conda, not conda-build. You can also reproduce it with `conda create -n test gcc=4.8.2=2 python=2.7.9=1 --dry`. 

The way conda currently handles explicit specs (specs that include the build string), you have to specify the full list of dependencies. https://github.com/conda/conda/issues/918 is related.  The relevant code is https://github.com/conda/conda/blob/375ae6412a1b3acd58aaec62b0c7fd79afb5bb51/conda/resolve.py#L633. I'm not sure why it takes a different code path if there is only one spec. 

I'd honestly like to completely remove the `explicit` function, but we can't do it because it leads to serious performance regressions.

**Comment by stuarteberg** [comment] 2015-05-13 23:34
>The way conda currently handles explicit specs (specs that include the build string), you have to specify the full list of dependencies.

Specify the full list of dependencies in a single `meta.yaml`?  I'm not sure I understand.  So, in the example above, `aaa/meta.yaml` would need to include not only `gcc` and `python`, but also their dependencies (`cloog`, `gmp`, `isl`, `mpc`, `mpfr`, `openssl`, `readline`, `sqlite`, `system`, `tk`, `zlib`, `pip`), and (recursively) any dependencies of those packages, and so on?

**Comment by msarahan** [comment] 2017-12-13 14:44
I believe this is solved.  Closing.  Please comment if this is still an issue.

**Closed by msarahan** 2017-12-13 14:44 UTC
