### ISSUE TITLE
conda-build unable to extract tar.xz files on Windows Python2.7/vc9

### ISSUE THREAD

**Issue by dschreij** [conda/conda-build#1536] opened 2016-11-15 17:39 UTC
I just pushed a recipe to conda-forge and it builds correctly on Windows for Python 3.*, but with Python 2.7/vc9 it reports the following:

~~~
Source cache directory is: C:\Miniconda\conda-bld\src_cache
Downloading source to cache: flac-1.3.1.tar.xz
Downloading http://downloads.xiph.org/releases/flac/flac-1.3.1.tar.xz
Success
Extracting download
unxz is required to unarchive .xz source files.

Command exited with code 1
~~~

It seems as if `unxz` is only missing for this version of vc and/or python.

The recipe can be found here: https://github.com/dschreij/staged-recipes/tree/sdl2_mixer/recipes/flac

Sadly, the source is not available in any other archive format, so I'm stuck with tar.xz.

**Comment by msarahan** [comment] 2016-11-15 19:16
xz can't be compiled with VS 2008.  It uses C99, which VS didn't support adequately until VS 2013.

xz as a standalone package would be feasible - built only as an executable that depended on VS 2015 runtime.  You can put in a pull request or issue requesting the package change at continuumIO/anaconda-recipes.  I must warn you, it may be some time before we can get to it.

This is not a bug with conda-build, though.  Closing this issue.

**Closed by msarahan** 2016-11-15 19:16 UTC

**Comment by dschreij** [comment] 2016-11-15 21:10
Right then, that sounds like a lot of trouble for a format which is rarely used. I think I am going to find another solution for this problem, maybe create a downloadable zip myself and link to that.
