### ISSUE TITLE
Custom channel usage fails due to remote channel index inconsistency

### ISSUE THREAD

**Issue by asilenzi** [conda/conda-build#3996] opened 2020-07-24 11:30 UTC
### Actual Behavior

I am not sure this is an issue with `conda index` or a misunderstanding on my part on how to create a custom channel.

In our current solution, we create a local custom channel to allow the deployment of conda environments to machines that are cut from the internet.

To do that we mirror the packages using `conda mirror`, upload these to our internal server and rebuild
the index using `conda index` on that server.

The package we install depends from a tight description of the environment (all packages versions are pinned down) for reproducibility's sake.

This installation worked for the past months, until few days ago.
The symptom was that the environment could not be resolved due to conflicts.

After some investigation, we found out that the conda-forge index is not matching with what is generated by `conda-index`

for example:

the content of `index.json` in [linux-64/sqlite-3.32.3-hcee41ef_1.tar.bz2] (ttps://conda.anaconda.org/conda-forge//linux-64/sqlite-3.32.3-hcee41ef_1.tar.bz2) is:

```
{
  "arch": "x86_64",
  "build": "hcee41ef_1",
  "build_number": 1,
  "depends": [
    "libgcc-ng >=7.5.0",
    "ncurses >=6.1,<6.2.0a0",
    "readline >=8.0,<9.0a0"
  ],
  "license": "Public-Domain (http://www.sqlite.org/copyright.html)",
  "name": "sqlite",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1594304296672,
  "version": "3.32.3"
}
```
However the corresponding entry in the conda-forge [repodata.json](https://conda.anaconda.org/conda-forge/linux-64/repodata.json) is :
```
    "sqlite-3.32.3-hcee41ef_1.tar.bz2": {
      "build": "hcee41ef_1",
      "build_number": 1,
      "depends": [
        "libgcc-ng >=7.5.0",
        "ncurses >=6.1,<6.3.0a0",
        "readline >=8.0,<9.0a0"
      ],
      "license": "Public-Domain (http://www.sqlite.org/copyright.html)",
      "md5": "eba59aaa700c4787661b55a8aa3541a7",
      "name": "sqlite",
      "sha256": "92b004539613e6093bb5b126b0267031c039e01cf828fc404507adfec1670470",
      "size": 1445533,
      "subdir": "linux-64",
      "timestamp": 1594304296672,
      "version": "3.32.3"
    },
```

The bit that got our system unable to install is the difference in the `depends` list.

the one built from `conda index` has:
```
['libgcc-ng >=7.5.0', 'ncurses >=6.1,<6.2.0a0', 'readline >=8.0,<9.0a0']
```
while in the index of `conda-forge has:
```
['libgcc-ng >=7.5.0', 'ncurses >=6.1,<6.3.0a0', 'readline >=8.0,<9.0a0']
```

This issue is not limited to the package I used as an example.

I am currently working around this by "amending" the `repodata.json` after creation, which is not ideal.

Thanks a lot for your support

### Expected Behavior

Either the custom channel index should match exactly the one mirrored from the remote (is this a `conda-mirror` issue then?) or conda-forge should use `conda index`.

### Steps to Reproduce

a recipe with depending on "ncurses==6.2_he1b5a44_1" and "sqlite==3.32.3-hcee41ef_1"
will build against `conda-forge` but not against a custom channel.

##### `Output of conda info`

```
     active environment : base
    active env location  #######/miniconda3
            shell level : 1
       user config file : ######/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.12
       base environment :  #######/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache :  #######/miniconda3/pkgs
                           #######/.conda/pkgs
       envs directories : /afs/desy.de/user/x/xkarabo/miniconda3/envs
                           #######/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.4 Linux/2.6.32-754.3.5.el6.x86_64 scientific/6.10 glibc/2.12
                UID:GID : 35540:3555
             netrc file : None
           offline mode : False
```

**Comment by marcelotrevisani** [comment] 2020-07-24 11:36
I believe you might be facing some problems regarding the mix of channels in your environment
Could you please also give us the result of ``conda list`` ?

If you are trying to just ship an entire conda env to be used in another machine, you can use ``conda-pack``, that should be sufficient for you, I believe

**Comment by marcelotrevisani** [comment] 2020-07-24 11:45
Can you also give us the full log of the conda-build ?

**Comment by asilenzi** [comment] 2020-07-24 11:46
Hey Marcelo! Thanks for the quick response!

here is the result of `conda list`

```
# packages in environment at $HOME/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
beautifulsoup4            4.9.1                    py37_0  
brotlipy                  0.7.0           py37h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37he30daa8_1  
chardet                   3.0.4                 py37_1003  
conda                     4.8.3                    py37_0  
conda-build               3.18.11                  py37_0  
conda-package-handling    1.6.1            py37h7b6447c_0  
cryptography              2.9.2            py37h1ba5d50_0  
filelock                  3.0.12                     py_0  
glob2                     0.7                        py_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
jinja2                    2.11.2                     py_0  
libarchive                3.4.2                h62408e4_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
liblief                   0.10.1               he6710b0_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libxml2                   2.9.10               he19cac6_1  
lz4-c                     1.9.2                he6710b0_0  
markupsafe                1.1.1            py37h14c3975_1  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1g               h7b6447c_0  
patchelf                  0.11                 he6710b0_0  
pkginfo                   1.5.0.1                  py37_0  
psutil                    5.7.0            py37h7b6447c_0  
py-lief                   0.10.1           py37h403a769_0  
pycosat                   0.6.3            py37h7b6447c_0  
pycparser                 2.20                       py_2  
pyopenssl                 19.1.0                     py_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.4                h265db76_1  
python-libarchive-c       2.9                        py_0  
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py37h7b6447c_1  
readline                  7.0                  h7b6447c_5  
requests                  2.24.0                     py_0  
ripgrep                   11.0.2               he32d670_0  
ruamel_yaml               0.15.87          py37h7b6447c_1  
setuptools                49.2.0                   py37_0  
six                       1.15.0                     py_0  
soupsieve                 2.0.1                      py_0  
sqlite                    3.32.3               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.47.0                     py_0  
urllib3                   1.25.9                     py_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h0b5b093_0
```

here is the result of `conda info --all`

```
     active environment : base
    active env location : $HOME/miniconda3
            shell level : 1
       user config file : $HOME/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.12
       base environment : /afs/desy.de/user/x/xkarabo/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $HOME/miniconda3/pkgs
                         $HOME.conda/pkgs
       envs directories : $HOME/miniconda3/envs
                          $HOME.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.4 Linux/2.6.32-754.3.5.el6.x86_64 scientific/6.10 glibc/2.12
                UID:GID : 35540:3555
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  $HOME/miniconda3

sys.version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
...
sys.prefix: /afs/desy.de/user/x/xkarabo/miniconda3
sys.executable: /afs/desy.de/user/x/xkarabo/miniconda3/bin/python
conda location: /afs/desy.de/user/x/xkarabo/miniconda3/lib/python3.7/site-packages/conda
conda-build: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-build
conda-convert: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-convert
conda-debug: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-debug
conda-develop: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-develop
conda-env: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-env
conda-index: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-index
conda-inspect: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-inspect
conda-metapackage: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-metapackage
conda-render: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-render
conda-skeleton: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: base
CONDA_EXE: /afs/desy.de/user/x/xkarabo/miniconda3/bin/conda
CONDA_PREFIX: /afs/desy.de/user/x/xkarabo/miniconda3
CONDA_PROMPT_MODIFIER: (base) 
CONDA_PYTHON_EXE: /afs/desy.de/user/x/xkarabo/miniconda3/bin/python
CONDA_ROOT: /afs/desy.de/user/x/xkarabo/miniconda3
CONDA_SHLVL: 1
MANPATH: /usr/sue/man:/opt/products/man:/usr/share/man:/usr/afsws/man:/usr/X11/man:/usr/local/X11/man:/usr/local/man
MODULEPATH: /usr/share/Modules/modulefiles:/etc/modulefiles
PATH: .
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
XFILESEARCHPATH: /usr/lib/X11/%T/%N:/usr/local/X11/lib/X11/%T/%N
```

Yes, we were considering using `conda-pack` instead of a strict recipe.

**Comment by marcelotrevisani** [comment] 2020-07-24 11:53
I tried to reproduce this problem and I was not able to.

I create the following example:
```yaml
package:
  name: foo
  version: 1.0.0

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python


```

and it worked fine

I believe you are facing some problems with your cache
could you please execute ``conda clean --all --yes`` and after that can you try to build your recipe again?

**Comment by marcelotrevisani** [comment] 2020-07-24 12:03
Even if I pin the versions in the requirements section it is working fine

**Comment by asilenzi** [comment] 2020-07-24 12:09
The recipes are built in a clean environment on CI. The command you post is executed before the package creation (which makes me think we are not completely off the mark).

I will make more clear reproduction steps

**Comment by marcelotrevisani** [comment] 2020-07-24 12:12
I would recommend you to use the ``conda-forge`` docker image and try to reproduce the problem there please
https://github.com/conda-forge/docker-images/tree/master/miniforge3

**Comment by asilenzi** [comment] 2020-07-24 12:18
Thanks for the info, I will get back to you

**Comment by asilenzi** [comment] 2020-07-24 12:45
I use an even simpler conda recipe than the example you gave:

```
package:
  name: foo
  version: 1.0.0

build:
  number: 0
  noarch: python

requirements:
  host:
    - ncurses =6.2=he1b5a44_1
    - sqlite =3.32.3=hcee41ef_1
  run:
    - ncurses =6.2=he1b5a44_1
    - sqlite =3.32.3=hcee41ef_1
```

I build it successfully with: `conda build . -c conda-forge`

To simulate an isolated system, I remove all channel from my configuration.

I create a local package mirror with:
`conda mirror --upstream-channel conda-forge --target-directory /path/to/conda_issue3996/mirror --platform linux-64 --config mirror.yaml`

The content of the `mirror.yaml` file matches exactly the versions and builds imported during `conda build`:
```
blacklist:
  - name: "*"
whitelist:
  - name: "ncurses"
    version: "6.2"
    build: "he1b5a44_1"
  - name: "sqlite"
    version: "3.32.3"
    build: "hcee41ef_1"
  - name: "_libgcc_mutex"
    version: "0.1"
    build: "conda_forge"
  - name: "_openmp_mutex"
    version: "4.5"
    build: "0_gnu"
  - name: "libgcc-ng"
    version: "9.2.0"
    build: "h24d8f2e_2"
  - name: "libgomp"
    version: "9.2.0"
    build: "h24d8f2e_2"
  - name: "libstccxx-ng"
    version: "9.2.0"
    build: "hdf63c60_2"
  - name: "readline"
    version: "8.0"
    build: "he28a2e2_2"
```

after that, I build an index with
`conda index /path/to/conda_issue3996/mirror`

At this point, this command
`conda create -n env3996_online foo -c local -c conda-forge`
works.

But the command:
`conda create -n env3996_local foo -c local -c file:///path/to/conda_issue3996/mirror`

fails with this error log:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package sqlite conflicts for:
foo -> sqlite[version='3.32.3,>=3.32.3,<4.0a0',build=hcee41ef_1]
Package python conflicts for:
foo -> python
Package ncurses conflicts for:
foo -> ncurses==6.2=he1b5a44_1
Package python_abi conflicts for:
foo -> python_abi=3.6[build=*_cp36m]
```

**Comment by asilenzi** [comment] 2020-07-24 12:49
If I edit the `/path/to/conda_issue3996/mirror/linux-64/repodata.json` but changing the `depends` portion of the `sqlite` package from `"ncurses >=6.1,<6.2.0a0",` to "ncurses >=6.1,<6.3.0a0" (which is what is available in conda-forge). The installation succeeds.

**Comment by marcelotrevisani** [comment] 2020-07-24 14:14
Oh, I see
I was just checking some stuffs here, and now I know what is happening. Basically, ``conda-forge`` is a bit different, because we patch the ``repodata.json``
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe

And because of that the mirroring will not work properly because you may face some metadata differences between the package on anaconda and the repodata. The only way for you as you are using strict ``conda-forge`` you will need to follow what ``conda-forge`` is doing.
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L577

You can try to use those scripts to modify the repodata.json everytime you run ``conda index``. I am afraid that is the only solution for your case.

As this is a problem related to ``conda-build`` I am closing this issue, any problem in the future please fell free to reopen it or to create another issue

**Closed by marcelotrevisani** 2020-07-24 14:14 UTC

**Comment by asilenzi** [comment] 2020-07-24 15:24
Thanks for the help!

I will either keep the patch I developed or borrow that [script](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py) until we regroup to use `conda-pack`.
