### ISSUE TITLE
lock issues (mutex)

### ISSUE THREAD

**Issue by neok-m4700** [conda/conda-build#2484] opened 2017-11-10 12:33 UTC
If have issues when building multiple recipes **concurrently** (multiple instances of `$ conda build <...>`, runing at the same time).

As I recall the issue appears since **3.0.28** and not with **3.0.27**

I seems that the lock acquired by the first instance is not taken into account by the second when writing to .json files. This lead to corrupted files and failure.

The issue appears with the file `conda-bld/linux-64/.paths.json` (which by the way grows unreasonably up to 102 MB in my case ?) ...

```python
Traceback (most recent call last):
  File "<...>/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "<...>/conda_build/build.py", line 1777, in build_tree
    notest=notest,
  File "<...>/conda_build/build.py", line 1240, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "<...>/conda_build/build.py", line 792, in bundle_conda
    timeout=metadata.config.timeout)
  File "<...>/conda_build/index.py", line 147, in update_index
    channel_name)
  File "<...>/conda_build/index.py", line 220, in update_subdir_index
    paths = read_json_caching_file(paths_path)
  File "<...>/conda_build/index.py", line 215, in read_json_caching_file
    return json.load(fi)
  File "<...>/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "<...>/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "<...>/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "<...>/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1832628 column 17 (char 76452462)
```
Using `Anaconda 5.0.1` on linux-64

**Comment by neok-m4700** [comment] 2017-11-10 13:02
A simple patch, avoiding failure, but not correcting the issue:

```patch
--- index.py	2017-11-10 13:58:29.058902460 +0100
+++ index2.py	2017-11-10 13:59:05.507083197 +0100
@@ -198,10 +198,13 @@
         if not force:
 
             def read_json_caching_file(path):
-                if isfile(path):
-                    with open(path) as fi:
-                        return json.load(fi)
-                else:
+                try:
+                    if isfile(path):
+                        with open(path) as fi:
+                            return json.load(fi)
+                    else:
+                        return {}
+                finally:
                     return {}
             index = read_json_caching_file(index_path)
             about = read_json_caching_file(about_path)

```

**Comment by msarahan** [comment] 2017-11-10 16:49
Thanks for reporting.  I'll add a lock around that stuff.

**Comment by msarahan** [comment] 2017-11-10 17:31
Scratch that.  Locks are already there. =(

I doubt there's any simple set of recipes that can trigger this, since it's basically a race condition, but if you do have such a reproducer, please let me know.  It'll make this much easier to debug.

**Comment by msarahan** [comment] 2017-11-10 18:00
I think https://github.com/conda/conda-build/pull/2486 might be the answer.  @neok-m4700 can you please test that PR?

**Comment by neok-m4700** [comment] 2017-11-10 19:58
I've tested the PR and the issue persists. It's always a pain to reproduce race conditions, but here is a one-liner with a dummy recipe to reproduce the issue:

```bash
#!/usr/bin/env bash
# github.com/conda-forge/six-feedstock/blob/master/recipe/meta.yaml
for i in {1..10}; do conda build six &>log.$i & pids+=($!); sleep .01; done
wait ${pids[@]}
grep JSONDecodeError log*
```

**Comment by msarahan** [comment] 2017-11-10 20:34
Are you rebuilding the same recipe in practice, or is that just for this test?  That's more likely to cause problems, with the way that folder names are based on package name plus a timestamp.

**Comment by neok-m4700** [comment] 2017-11-10 20:58
No it is just a degenerated test to reproduce the issue, but I usually build 2 to 3 different recipes at the same time (so timesteps and folders name are not involved here), and I find rather inconvenient to fail on sporadic issues like this one. And since I never encountered this particular issue (using conda-build 2.0 --> 3.0.27) from my point of view it is a regression (I've had around 10 failures on a 500+ recipes build stack) ...

Thanks for helping though, I will dig into this this WE an hopefully propose a PR ...

**Comment by msarahan** [comment] 2017-11-10 21:11
Yeah, it's definitely a regression.  Sorry.  I wish I understood why the locking isn't doing what it's supposed to do.  I'll also try to work on it, but please don't let that hold you up.

**Comment by msarahan** [comment] 2018-09-11 16:06
closing as I'm not sure this is still an issue. Happy to reopen if this would actually be useful.

**Closed by msarahan** 2018-09-11 16:06 UTC
