### ISSUE TITLE
Build dependencies not being properly installed

### ISSUE THREAD

**Issue by yehted** [conda/conda-build#1310] opened 2016-09-01 23:12 UTC
In my meta.yaml, I have yaml as one of my build dependencies
```yaml
requirements:
  build:
    - python
    - setuptools
    - yaml
```
When I run ```conda build .```, it says 
```
The following NEW packages will be INSTALLED:
    openssl:    1.0.2h-1
    pip:        8.1.2-py27_0
    python:     2.7.12-1
    readline:   6.2-2
    setuptools: 26.1.1-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    yaml:       0.1.6-0
    zlib:       1.2.8-3
```
Inside my ```setup.py```, I import yaml as the very first line, because I read the name of the package and the version number from ```meta.yaml```. (If this is not the right way to do it, please let me know). But the build fails with an ```ImportError: No module named yaml```.  When I go into the conda-bld/build_folder/build_environment directory, yaml is indeed NOT in the site-packages

I'm 99% certain this worked pre-version 2.0.0

**Comment by msarahan** [comment] 2016-09-02 00:03
Importing yaml *should* work here, but this is not the right way to do it.  

In general, it is better to have meta.yaml reflect setup.py, not the other way around.  The reason why is that your Python package can then exist on PyPI and in conda-land, and you can take advantage of cool tools to automatically get the version from your version control repo (using perhaps versioneer or setuptools-scm).  There's an example of how to get information from setup.py in http://conda.pydata.org/docs/building/meta-yaml.html#templating-with-jinja at the bottom of that section.

I'm curious about the bad environment, though.  What folders are present?  In particular, is there more than one "build_folder" - the one with many numbers - for this build?  That may indicate a bug where the build id is changing in mid-build, and only one of them has the correct packages installed.

If this is a recipe you can share, or if you can reproduce with a simple example, I'll dig in.

**Comment by msarahan** [comment] 2016-09-02 01:21
I have seen this issue in a test environment when building setuptools.  In my case, an ```__init__.py``` file was missing from the setuptools folder, which was preventing successful import.  It sounds like your issue might be different, though.

**Comment by yehted** [comment] 2016-09-02 14:18
Thanks for the info on versioning, I will definitely try that route. However, here is a simple recipe that reproduces the issue. You are indeed correct that there is more than one build folder; perhaps you are right about the build id changing mid-build.

```yaml
package:
  name: my_conda_library
  version: 0.1.0

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - yaml

  run:
    - python
    - pandas

test:
  requires:
    - nose
```

setup.py:
```python
import yaml
from setuptools import setup, find_packages

with open('meta.yaml', 'r') as f:
    meta = yaml.load(f)

version = meta['package']['version']
name = meta['package']['name']

setup(
    name=name,
    version=version,
    description='testing conda libraries',
    packages=find_packages()
    )
```

directory structure:
```
.
|-- build.sh
|-- meta.yaml
|-- my_conda_library
|   |-- __init__.py
|   |-- my_module.py
|   `-- tests
|       |-- __init__.py
|       `-- test_my_module.py
`-- setup.py
```

**Comment by msarahan** [comment] 2016-09-02 19:15
Thanks, I am able to reproduce.  I'll hopefully have a fix shortly.

**Comment by msarahan** [comment] 2016-09-02 19:34
Sorry, this is a lot simpler than I thought.  The ```yaml``` package is the compiled C library.  You want the ```pyyaml``` package.  By making that change, your test works fine.

I'm going to close this issue, but please reopen it or open a new issue if you have further questions.

**Closed by msarahan** 2016-09-02 19:34 UTC
