### ISSUE TITLE
Bug when environment variables contain  '='

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#1042] opened 2016-06-21 22:54 UTC
The latest release of conda-build improperly mangles environment variables that contain the "=" character.  As an example, if you set `export CFLAGS=-fvisibility=hidden` in your shell and then call `conda-build`, `conda-build` will actually invoke the `build.sh` with `CFLAGS` set to `-fvisibility`, which obviously breaks gcc.

You can see the error in practice in this log: https://travis-ci.org/omnia-md/conda-recipes/jobs/139170394#L2575

The bug is here: https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L388-L389. It's pretty obvious if you look at that line of code.

cc: https://github.com/omnia-md/conda-recipes/issues/546 @mpharrigan @marscher

**Comment by msarahan** [comment] 2016-06-21 23:18
Thanks for identifying the issue.  I'll get that fixed quickly.

**Comment by mpharrigan** [comment] 2016-06-21 23:37
What's the intended behaviour here? The documentation says that no environment variables should pass through

http://conda.pydata.org/docs/building/environment-vars.html#inherited-environment-variables

**Comment by msarahan** [comment] 2016-06-22 00:01
New behavior is that environment variables that change as part of activation of the build environment do pass through.  We were manually setting PATH for the _build and _test environments, but that leaves out packages that potentially set environment variables on activation (GDAL is perhaps the most notorious for this.

Otherwise, that documentation is correct.

**Comment by msarahan** [comment] 2016-06-22 20:17
Fixed by #1044, part of 1.21.1 release.

**Comment by marscher** [comment] 2016-06-22 20:17
Thank you for the quick fix!

**Closed by msarahan** 2016-06-22 20:17 UTC
