### ISSUE TITLE
Problem installing Sphinx-1.3b2 with pipbuild

### ISSUE THREAD

**Issue by ngbrown** [conda/conda-build#323] opened 2015-02-10 04:55 UTC
```
C:\Windows\system32>conda pipbuild Sphinx --release 1.3b2
Fetching package metadata: ....
Creating standard recipe for sphinx-1.3b2
Using url https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.3b2.tar.gz (
3.1 MB) for Sphinx.
Downloading Sphinx (use --no-download to skip this step)
Unpacking Sphinx...
done
working in c:\users\nb\appdata\local\temp\tmpt1ripmconda_skeleton_Sphinx
Fetching package metadata: ......
Solving package specifications: .
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.9               |                1        18.8 MB

The following NEW packages will be INSTALLED:

    numpy:      1.9.1-py27_0
    python:     2.7.9-1
    pyyaml:     3.11-py27_0
    setuptools: 12.0.5-py27_0

Fetching packages ...
python-2.7.9-1 100% |###############################| Time: 0:00:20 947.47 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
Applying patch: 'c:\\users\\nb\\appdata\\local\\temp\\tmpt1ripmconda_skeleton_Sp
hinx\\pypi-distutils.patch'
Error:
    Did not find 'patch' in: C:\Anaconda\envs\_build\Scripts;C:\Anaconda\Scripts
;C:\cygwin\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;C:\Pr
ogram Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\libnvvp;C:\Windows\system32;C
:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C
:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\
OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\Windows Performan
ce Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Fil
es (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\12
0\Tools\Binn\;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\Git\cmd;C:
\Anaconda;C:\Anaconda\Scripts;c:\Users\nb\AppData\Local\atom\bin
    You can install 'patch' using apt-get, yum (Linux), Xcode (MacOSX),
    or conda, cygwin (Windows),


conda create -n _pipbuild_ --yes python pip
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\_pipbuild_:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-6.0.6                  |           py27_0         1.5 MB

The following NEW packages will be INSTALLED:

    pip:        6.0.6-py27_0
    python:     2.7.9-1
    setuptools: 12.0.5-py27_0

Fetching packages ...
pip-6.0.6-py27 100% |###############################| Time: 0:00:02 711.61 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
#
# To activate this environment, use:
# > activate _pipbuild_
#
C:\Anaconda\envs\_pipbuild_/bin/pip install Sphinx==1.3b2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-pipbuild-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 77, in
 main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in a
rgs_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 347, i
n execute
    build_package(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 303, i
n build_package
    directory, dependencies = make_recipe(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 245, i
n make_recipe
    depends = get_all_dependencies(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 215, i
n get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I installed patch with `conda install patch` and then ran the above command again, and a different error happened.

```
C:\Windows\system32>conda pipbuild Sphinx --release 1.3b2
Fetching package metadata: ....
Creating standard recipe for sphinx-1.3b2
Using url https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.3b2.tar.gz (
3.1 MB) for Sphinx.
Downloading Sphinx (use --no-download to skip this step)
Using cached download
Unpacking Sphinx...
done
working in c:\users\nb\appdata\local\temp\tmpaliospconda_skeleton_Sphinx
Fetching package metadata: ......
Solving package specifications: .69 unparsed bytes left at the end of stream
file 1/1:        core.py
 hunk no.1 doesn't match source file at line 165
  expected:
  actual  :                 raise SystemExit, "error: " + str(msg)
source file is different - core.py

Applying patch: 'c:\\users\\nb\\appdata\\local\\temp\\tmpaliospconda_skeleton_Sp
hinx\\pypi-distutils.patch'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 131, i
n main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in a
rgs_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 142, i
n execute
    pypi.main(args, parser)
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 407, in main
    run_setuppy(src_dir, tempdir, args)
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 596, in run_set
uppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda\lib\site-packages\conda_build\source.py", line 209, in apply
_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "C:\Anaconda\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Anaconda\\Scripts\\patch.bat', '-p
0', '-i', 'c:\\users\\nb\\appdata\\local\\temp\\tmpaliospconda_skeleton_Sphinx\\
pypi-distutils.patch']' returned non-zero exit status -1

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: C:\Anaconda\envs\_pipbuild_
C:\Anaconda\envs\_pipbuild_/bin/pip install Sphinx==1.3b2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-pipbuild-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 77, in
 main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in a
rgs_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 347, i
n execute
    build_package(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 303, i
n build_package
    directory, dependencies = make_recipe(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 245, i
n make_recipe
    depends = get_all_dependencies(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 215, i
n get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

```
C:\Windows\system32>conda info
Current conda install:

             platform : win-64
        conda version : 3.8.4
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.5.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by remram44** [comment] 2016-01-02 18:08
Looks like a duplicate of #119.

**Comment by msarahan** [comment] 2016-01-02 18:24
Please install the patch package and post back if it works or if you still have issues.

**Comment by msarahan** [comment] 2018-05-24 16:30
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package

**Closed by msarahan** 2018-05-24 16:30 UTC
