### ISSUE TITLE
run_exports not applied when channel does not provide channeldata.json

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#3583] opened 2019-06-28 21:39 UTC
As of #3561, run exports are extracted from channeldata.json rather than the packages themselves.  This speeds up rendering time but will cause run exports to not be applied if the channel from which the package is supplied does not provide channeldata.json.  Most channels on Anaconda.org do not provide channeldata.json.

A simple example:

```
package:
  name: exporty
  version: 1.0.0

build:
  run_exports:
    strong:
      - exporty
```

```
package:
  name: example
  version: 1.0.0

requirements:
  build:
    - exporty
```

Building `exporty` and locally and rendering `example` gives a correct rendering with run_export applied:

```
$ conda render example/
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example
    version: 1.0.0
requirements:
    build:
        - exporty 1.0.0 0
    run:
        - exporty
extra:
    copy_test_source_files: true
    final: true
```

Using the uploaded `exporty` package on Anaconda.org results in no run_exports applied:

```
$ conda render -c jjhelmus example/
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example
    version: 1.0.0
requirements:
    build:
        - exporty 1.0.0 0
extra:
    copy_test_source_files: true
    final: true
```

**Comment by mariusvniekerk** [comment] 2019-06-30 14:45
@jjhelmus is this why we are missing run_exports for our conda-forge aarch64 and ppc64le packages?

**Comment by jjhelmus** [comment] 2019-07-01 15:13
> @jjhelmus is this why we are missing run_exports for our conda-forge aarch64 and ppc64le packages?

Yes, moving the effected conda-build aarch64 packages (3.18.6  3.18.5 3.18.4) to a broken label may be the easiest fix until this is changed in conda-build itself.

**Comment by minrk** [comment] 2019-07-02 14:28
There's something wrong with run_exports on linux-64 as well. When I run `conda render` on a package that has `fftw` as a host dependency, it's getting run_exports coming from builds of packages not in the host environment. Seems like something's amiss in general in the run_exports computation.

meta.yaml:

<details>

```yaml
$ cat test/meta.yaml
package:
  name: testing
  version: 1.0

source:

build:
  number: 1

requirements:
  build: []
  host:
    - fftw
  run:
    - fftw

```
</details>

`conda render --verbose test`

<details>

```yaml
Adding in variants from internal_defaults
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for testing
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: testing
    version: '1.0'
build:
    number: '1'
requirements:
    host:
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - fftw 3.3.8 nompi_h7f3a6c3_1105
    run:
        - fftw * mpi_openmpi_*
extra:
    copy_test_source_files: true
    final: true
```

</details>


`conda info`

<details>

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/4.9.125-linuxkit centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False
```

</details>

FWIW, I confirmed that this does not happen with conda-build 3.18.3 and does with 3.18.4-6.

**Comment by minrk** [comment] 2019-07-02 14:54
For further detail about what might make this case weird: there are three builds of fftw 3.3.8: `nompi_`, which has no run_exports, and 2x `mpi_{provider}` which have `run_exports: fftw * mpi_{provider}_*`. I'm guessing the new logic in #3561 is merging them somehow, or clobbering the one empty run_exports with one of the others.

**Comment by SylvainCorlay** [comment] 2019-07-03 17:19
Sadly, we released over 20 packages on the xeus stack making use of the broken version of conda build unfortunately, and there are as many binders that are broken.

**Comment by msarahan** [comment] 2019-07-03 17:35
Maybe it would be worth your time to add tests to the conda forge
infrastructure or whatever you use so that this doesn't bite you again. Or
perhaps a test in conda build's test suite?

**Comment by SylvainCorlay** [comment] 2019-07-03 17:44
We test that artefacts are properly produced. Although run-exports being completely ignored looks like a rather major issue for a release...

**Comment by msarahan** [comment] 2019-07-03 18:37
But you apparently don't test that libraries are correctly loaded at test time - if you did, you would have caught this.

Run-exports is not completely ignored.  It works fine for channels that have channeldata.json.  It is tested, and those tests pass.  Since you depend on a channel that does not have channeldata.json, perhaps it is worth your time to invest in conda-build so that it won't break for you in the future.

**Comment by SylvainCorlay** [comment] 2019-07-03 19:37
Yeah we are not testing the produced runtime but that should be easily fixed (trying to launch the kernel at least if not running the test suite).

Investing into conda-build core at the moment would really hard in terms of bandwidth for the team.

**Comment by msarahan** [comment] 2019-07-03 19:53
I have never asked you to fix it. I have asked you to help write tests for functionality that you depend on, especially when our tests cover our user cases, but not yours.

**Comment by SylvainCorlay** [comment] 2019-07-03 22:03
>  I have asked you to help write tests for functionality that you depend on.

Sounds good. Would be happy to add such tests!

**Comment by minrk** [comment] 2019-07-04 12:00
Testing issues like this would be helped a lot by conda-build supporting multiple test envs. For instance, this issue snuck through on mpich because the test environment had the compiler packages, which included the dependencies missing from run_exports.  It would also enable testing e.g. ABI compatibility by running tests against latest and oldest allowed versions of dependencies, which are currently not testable.

**Comment by minrk** [comment] 2019-07-12 11:44
FWIW, this does not appear to be fixed in 3.18.7. [this aarch64 build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=48842&view=logs&jobId=e850670b-9c4b-5777-abd3-3d8cda8632a0&taskId=65db09fb-3d92-5ae9-0ca9-6a8bcf08e26a&lineStart=22607&lineEnd=22607&colStart=1&colEnd=46). is still missing run_export s from gfortran_linux;

See in the tests for openmpi:

```
The following NEW packages will be INSTALLED:

    mpi:     1.0-openmpi      conda-forge
    openmpi: 4.0.1-hc99cbb1_2 local     
```

when it should have libgfortran according to the strong run_exports on [gfortran_linux-aarch64](https://anaconda.org/c4aarch64/gfortran_linux-aarch64/files), since it has a build dependency on all the compilers (c, cxx, fortran).

**Comment by ax3l** [comment] 2019-07-12 19:19
But we are not yet using conda-build 3.18.7 but instead 3.17.8 in the linked PR, no?

**Comment by minrk** [comment] 2019-07-16 14:42
That PR's using 3.18.7

**Comment by xhochy** [comment] 2019-07-17 11:14
Another failure is https://github.com/conda-forge/icu-feedstock/pull/25/checks?check_run_id=170794956 in https://github.com/conda-forge/icu-feedstock/pull/25

**Comment by jjhelmus** [comment] 2019-07-18 20:34
Closing this particular issue since the lack of channeldata.json has been fixed.  The related issue where different builds/hashes express different `run_exports` can be discussed in #3617.

**Closed** 2019-07-18 22:03 UTC
