### ISSUE TITLE
conda build fails with ImportError: No module named base.constants

### ISSUE THREAD

**Issue by shjoshi** [conda/conda-build#1530] opened 2016-11-14 01:46 UTC
Hello,

 I upgraded my conda (miniconda) installation. It's now running version 4.1.12
 I tried to build a conda recipe and got the following error: 
 I was able to build recipes without any issues before. 
 
Traceback (most recent call last):
  File "/Users/joe/miniconda2/bin/conda-build", line 4, in <module>
    import conda_build.cli.main_build
  File "/Users/joe/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 16, in <module>
    import conda_build.api as api
  File "/Users/joe/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/Users/joe/miniconda2/lib/python2.7/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import string_types, binstar_upload
  File "/Users/joe/miniconda2/lib/python2.7/site-packages/conda_build/conda_interface.py", line 27, in <module>
    from conda.base.constants import SEARCH_PATH
ImportError: No module named base.constants

**Comment by msarahan** [comment] 2016-11-14 13:28
Thanks for this report, and sorry for the issue.  This issue is a duplicate of #1527 and has been fixed in #1528.  I will be tagging a new release today.

You can update conda in the meantime - this is a backwards compatibility issue, and the new version of conda is fine.  Note that conda-forge's conda version is still stuck at 4.1, so make sure that you get conda from defaults.

**Closed by msarahan** 2016-11-14 13:28 UTC
