### ISSUE TITLE
Error about mercurial, while it is not being used.

### ISSUE THREAD

**Issue by dschreij** [conda/conda-build#1497] opened 2016-11-01 18:31 UTC
When trying to build my recipe for sdl2, which worked correctly before, I now get the error `ValueError: Your recipe uses mercurial in build, but mercurial does not yet support Python 3.  Please handle all of your mercurial actions outside of your build script.`, even though I am not using any mercurial feature at all.

Here is the full traceback (if it is of any use):

~~~
PS > conda build sdl2
BUILD START: sdl2-2.0.4-vc14_0
    (actual version deferred until further download or env creation)
updating index in: C:\Anaconda3\conda-bld\win-64
updating index in: C:\Anaconda3\conda-bld\noarch

The following NEW packages will be INSTALLED:

    cmake:          3.3.1-0
    pip:            8.1.2-py35_0
    python:         3.5.2-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 234, in execute
    already_built=None, config=config)
  File "C:\Anaconda3\lib\site-packages\conda_build\api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 1099, in build_tree
    config=recipe_config)
  File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 654, in build
    raise ValueError("Your recipe uses mercurial in build, but mercurial"
ValueError: Your recipe uses mercurial in build, but mercurial does not yet support Python 3.  Please handle all of your mercurial actions outside of your build script.
~~~

**Comment by msarahan** [comment] 2016-11-01 18:34
duplicate of #1488 I think.  Closing to consolidate discussion there.

**Closed by msarahan** 2016-11-01 18:34 UTC

**Comment by msarahan** [comment] 2016-11-01 18:38
I should add that if you can link to your SDL2 recipe, that would be extremely helpful.

**Comment by dschreij** [comment] 2016-11-01 18:41
Sure, here it is: https://github.com/conda-forge/staged-recipes/tree/d3efa39c64534d6ead3faebd6ec9a97d5d5d2550/recipes/sdl2

**Comment by msarahan** [comment] 2016-11-01 19:02
yep, same issue as #1488.  Crappy overly broad regex.  It's finding https://github.com/conda-forge/staged-recipes/blob/d3efa39c64534d6ead3faebd6ec9a97d5d5d2550/recipes/sdl2/meta.yaml#L45 and getting confused.  Fix coming very soon.
