### ISSUE TITLE
Unsatisfiable dependencies for platform win-32: ['vs2008_win-32']

### ISSUE THREAD

**Issue by tovrstra** [conda/conda-build#2263] opened 2017-08-07 13:37 UTC
I'm trying to use the generic dependency on a C compiler in my meta.yml file (`{{ compiler('c') }}`) but that does not seem to work when building the package on AppVeyor. 

`meta.yml`: https://github.com/tovrstra/molmod/blob/f3d1201ac3b7b24618e6d194d9dbd0384038d3ea/tools/conda.recipe/meta.yaml

Here are the outputs on AppVeyor: https://ci.appveyor.com/project/tovrstra/molmod/build/67

Conda build errors with the following message: https://ci.appveyor.com/project/tovrstra/molmod/build/67/job/w7w6i572sxykq7wy#L184

    Traceback (most recent call last):
      File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
        sys.exit(conda_build.cli.main_build.main())
      File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 387, in main
        execute(sys.argv[1:])
      File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 378, in execute
        noverify=args.no_verify)
      File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 184, in build
        need_source_download=need_source_download, config=config, variants=variants)
      File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1715, in build_tree
        notest=notest,
      File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 885, in build
        output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
      File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 489, in expand_outputs
        for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
      File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 1720, in get_output_metadata_set
        permit_unsatisfiable_variants=permit_unsatisfiable_variants)
      File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 623, in finalize_outputs_pass
        fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
      File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 274, in finalize_metadata
        permit_unsatisfiable_variants=permit_unsatisfiable_variants)
      File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 112, in get_env_dependencies
        channel_urls=tuple(m.config.channel_urls))
      File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 688, in get_install_actions
        raise DependencyNeedsBuildingError(exc, subdir=subdir)
    conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-32: ['vs2008_win-32']
    Command exited with code 1

The compiler is already installed on these instances, but probably it cannot be found.

A simple workaround is to omit the dependency and to load the environment variables for the MSVC compilers manually in `appveyor.yml`:

    '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'

Somehow this even works for MSVC 2008 (?) but I do get the following warning:

    Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0.  Use {{compiler('c')}} jinja2 in requirements/build or explicitly list compiler package as build dependency instead.

Is there a sane future-proof way to configure MSVC compilers with conda build? Thanks!

**Comment by msarahan** [comment] 2017-08-07 13:51
Sorry, the new compiler packages are not on the defaults channel yet.  If you use the c3i_test anaconda.org channel, the vs2008_win-64 and vs2015_win-64 should be available.  Recipes for these are:

meta.yaml:
```
package:
  name: vs2008
  version: "9.00.30729.1"

outputs:
  - name: vs2008_{{ target_platform }}
    script: install_activate.bat
    run_exports:
      - vc 9
about:
  summary: Activation and version verification of MSVC 9 (VS 2008) compiler
  license: BSD 3-clause
```

activate.bat:
```
:: Set env vars that tell distutils to use the compiler that we put on path
SET DISTUTILS_USE_SDK=1
SET MSSdk=1

:: http://stackoverflow.com/a/26874379/1170370
SET platform=
IF /I [%PROCESSOR_ARCHITECTURE%]==[amd64] set platform=true
IF /I [%PROCESSOR_ARCHITEW6432%]==[amd64] set platform=true

if defined platform (
set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\9.0"
)  ELSE (
set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0"
)
for /f "skip=2 tokens=2,*" %%A in ('reg query "%VSREGKEY%" /v InstallDir') do SET "VSINSTALLDIR=%%B"

if not "%VSINSTALLDIR%" == "" (
   :: Look in VS90COMNTOOLS
   set "VSINSTALLDIR=%VS90COMNTOOLS%"
)

if "%VSINSTALLDIR%" == "" (
   ECHO "Did not find VS in registry or in VS90COMNTOOLS env var - exiting"
   exit 1
)

echo "Found VS2008 at"
echo "%VSINSTALLDIR%"

SET "VS_VERSION=9.0"
SET "VS_MAJOR=9"
SET "VS_YEAR=2008"

set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"
set "MSYS2_ENV_CONV_EXCL=CL"

:: other things added by install_activate.bat at package build time

```

conda_build_config.yaml:
```
target_platform:
  - win-64
  - win-32
```

install_activate.bat:
```
mkdir "%PREFIX%\etc\conda\activate.d"
COPY "%RECIPE_DIR%\activate.bat" "%PREFIX%\etc\conda\activate.d\vs2008_compiler_vars.bat"

if "%ARCH%" == "64" (
    :: 64-bit
    echo SET "CMAKE_GENERATOR=Visual Studio 9 2008 Win64" >> "%PREFIX%\etc\conda\activate.d\vs2008_compiler_vars.bat"
) else (
    :: 32-bit
    echo SET "CMAKE_GENERATOR=Visual Studio 9 2008" >> "%PREFIX%\etc\conda\activate.d\vs2008_compiler_vars.bat"
)

echo . >> "%PREFIX%\etc\conda\activate.d\vs2008_compiler_vars.bat"

IF %target_platform% == "win-64" (
  set "target_platform=amd64"
  ) else (
  set "target_platform=x86"
  )

echo CALL "%%VSINSTALLDIR%%\..\..\VC\vcvarsall.bat" %target_platform% >> "%PREFIX%\etc\conda\activate.d\vs2008_compiler_vars.bat"

```

We'll try to get these packages up on defaults.  Unfortunately, these recipes depend completely on using conda-build 3, so they can't go on conda-forge until conda-forge switches over.

**Comment by msarahan** [comment] 2017-08-07 13:58
Whoops, should have looked: vs2008_win-32 is available on the c3i_test channel.  You don't need to build your own package with that recipe.  https://anaconda.org/c3i_test/vs2008_win-32

**Comment by tovrstra** [comment] 2017-08-07 15:34
Sweet! I'll give these at try and let you know how it works. Thank you for the detailed explanation!

**Comment by tovrstra** [comment] 2017-08-08 09:37
I've tested this on a minimal example project: https://github.com/tovrstra/python-cython-ci-example (See tovrstra/python-cython-ci-example#1. I'll try to make a comprehensive overview below.

AppVeyor
-----

https://ci.appveyor.com/project/tovrstra/python-cython-ci-example/build/85

AppVeyor, Py2.7, x86: Fail
AppVeyor, Py2.7, x64: Fail
AppVeyor, Py3.5, x86: Sucess
AppVeyor, Py3.5, x64: Fail
AppVeyor, Py3.6, x86: Sucess
AppVeyor, Py3.6, x64: Sucess

I'm not sure what is exactly going wrong but they all still report this warning, even though I'm now using `{{ compiler('c') }}`:
```
Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0.  Use {{compiler('c')}} jinja2 in requirements/build or explicitly list compiler package as build dependency instead.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0.  Use {{compiler('c')}} jinja2 in requirements/build or explicitly list compiler package as build dependency instead.
```

I'm seeing different types of errors:

**AppVeyor, Py2.7, x86: Fail**

```
C:\Miniconda\conda-bld\pycydemo_1502166298111\_h_env\etc\conda\activate.d>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\" /v InstallDir') do SET VSINSTALLDIR=%B 
ERROR: The system was unable to find the specified registry key or value.
\Microsoft was unexpected at this time.
```

**AppVeyor, Py2.7, x64: Fail**

```
(root) C:\Miniconda-x64\conda-bld\pycydemo_1502166454559\work>call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\..\..\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
```

```
C:\Miniconda-x64\conda-bld\pycydemo_1502166454559\_h_env\etc\conda\activate.d>VisualStudioVersion=9.0 
'VisualStudioVersion' is not recognized as an internal or external command,
operable program or batch file.
```

**AppVeyor, Py3.5, x64: Fail**

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Miniconda35-x64\conda-bld\pycydemo_1502166866047\_h_env\libs /LIBPATH:C:\Miniconda35-x64\conda-bld\pycydemo_1502166866047\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86" /LIBPATH:C:\Miniconda35-x64\conda-bld\pycydemo_1502166866047\_h_env\Library\lib "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64" /EXPORT:PyInit_extension build\temp.win-amd64-3.5\Release\pycydemo\extension.obj /OUT:build\lib.win-amd64-3.5\pycydemo\extension.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\pycydemo\extension.cp35-win_amd64.lib
python35.lib(python35.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1112
```

Travis-CI
-----

https://travis-ci.org/tovrstra/python-cython-ci-example/builds/262093460

Py2.7, Linux: Fail
Py2.7, OSX: Fail
Py3.5, Linux: Fail
Py3.5, OSX: Fail
Py3.6, Linux: Success
Py3.6, OSX: Fail

I'm getting two types of errors:

**Py2.7, Linux: Fail**
**Py3.5, Linux: Fail**


```
gcc -pthread -shared -L/home/travis/miniconda/conda-bld/pycydemo_1502166129968/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath=/home/travis/miniconda/conda-bld/pycydemo_1502166129968/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib,--no-as-needed -Wl,-O2,--sort-common,--as-needed,-z,relro -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-2.7/pycydemo/extension.o -L/home/travis/miniconda/conda-bld/pycydemo_1502166129968/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/pycydemo/extension.so
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
```

**Py2.7, OSX: Fail**
**Py3.5, OSX: Fail**
**Py3.6, OSX: Fail**

```
++++ xcodebuild -showsdks
++++ grep -q '\-sdk macosx10.9'
++++ echo 'This system is unsupported by this recipe.'
```

**Comment by msarahan** [comment] 2017-08-08 12:24
Yikes, sorry for the user unfriendliness here.  Some of these are bugs, some are missing implementations, and some are "features."  Let me explain.

Appveyor warnings: bug.  I haven't gotten that warning message to disappear when the compiler packages are present.

AppVeyor, Py2.7, x86: Fail: incomplete implementation.  We use the full VS2008 install internally, and I haven't fully ported over the fallback logic to use the VC compiler for python 2.7, which is what Appveyor uses.

AppVeyor, Py3.5, x64: Fail: bug.  Not sure exactly what the bug is, unfortunately.  Needs some debugging effort.

Linux: seems like you might be picking up a different compiler than the one that we ship on the c3i channel.  The one we ship is GCC 7.1, which has many new security features, especially in comparison to the GCC 4.8 that most of the build images use right now.  The error seems to indicate that that feature is missing, so you're picking up an older compiler somehow.  This could be a conda-build bug, but it's more likely that something you're doing in your recipe or software is not respecting the CC environment variable, which is how we tell things like Make which compiler to use.  Note that all of our compiler executables are prefixed.  There is no "gcc" file.  Instead, there is x86_64-something-something-gcc - so this is not a PATH problem.

Mac: This is a "feature" of the clang packages that we created for osx.  They are tied to a specific SDK version.  This ensures that the compatibility of the packages you build is well understood, but it comes at the cost of user unfriendliness here.  There are three solutions:

1. build on an older OSX VM, if available.  I believe that conda-forge has needed to do special work to get Travis CI to use 10.9.
2. Try to install the older SDK.  There are some SDKs for download at https://github.com/phracker/MacOSX-SDKs
3. Build a new clang package that targets newer osx, and forgo the backwards compatibilty.  The recipe we created for this is:

meta.yaml:
```
package:
  name: clang_{{ target_platform }}
  version: {{ macos_min_version }}

build:
  skip: True  [not osx]

outputs:
  - name: clang_{{ target_platform }}
    script: install-clang.sh
  - name: clangxx_{{ target_platform }}
    script: install-clangxx.sh
```

activate.sh:
```
#!/bin/bash

# check if clang exists. stderr is thrown away by dev/null
if hash clang 2>/dev/null && xcodebuild -showsdks | grep -q "\-sdk macosx@macos_min_version@"
then
    # for Mac OSX
    export CC=clang
    export CXX=clang++
    export MACOSX_DEPLOYMENT_TARGET="@macos_min_version@"
    export CMAKE_OSX_DEPLOYMENT_TARGET="@macos_min_version@"
    export CFLAGS="${CFLAGS} -mmacosx-version-min=@macos_min_version@"
    export CXXFLAGS="${CXXFLAGS} -mmacosx-version-min=@macos_min_version@"
    export CXXFLAGS="${CXXFLAGS} -stdlib=libc++"
    export LDFLAGS="${LDFLAGS} -headerpad_max_install_names"
    export LDFLAGS="${LDFLAGS} -mmacosx-version-min=@macos_min_version@"
    export LDFLAGS="${LDFLAGS} -lc++"
    export LINKFLAGS="${LDFLAGS}"
else
    echo "This system is unsupported by this recipe."
    exit 1
fi

```

conda_build_config.yaml:
```
target_platform:
  - osx-64
macos_min_version:
  - 10.9
zip_keys:
  -
    - target_platform
    - macos_min_version
```

install-clang.sh:
```
#!/bin/bash

mkdir -p ${PREFIX}/etc/conda/activate.d/

cp ${RECIPE_DIR}/activate.sh ${PREFIX}/etc/conda/activate.d/conda_"${PKG_NAME}".sh
# hard-code the sdk version we build for
sed -i '' "s/@macos_min_version@/${macos_min_version}/" ${PREFIX}/etc/conda/activate.d/conda_"${PKG_NAME}".sh
```

install-clangxx.sh:
```
#!/bin/bash

mkdir -p ${PREFIX}/etc/conda/activate.d/

cp ${RECIPE_DIR}/activate.sh ${PREFIX}/etc/conda/activate.d/conda_"${PKG_NAME}".sh
# hard-code the sdk version we build for
sed -i '' "s/@macos_min_version@/${macos_min_version}/" ${PREFIX}/etc/conda/activate.d/conda_"${PKG_NAME}".sh
```

**Comment by tovrstra** [comment] 2017-08-08 12:46
Thanks for the detailed reply! I will need some time to process this. Bear with me. :)

**Comment by tovrstra** [comment] 2017-08-09 05:14
P.S. The [project](https://github.com/tovrstra/python-cython-ci-example) I'm testing is very minimal, so it contains no custom scripts to modify environment variables, such as `CC`. Besides a very simple Cython project (using setuptools to install) there is only `.travis.yml`, `.appveyor.yml` and `tools/conda.recipe/meta.yml`. (The goal of this toy project is to get a free hosted CI+deployment working with conda for Cython projects, with minimal complexity.)

I should be able to reproduce the Linux problems locally and get them sorted out somehow. For OSX, Travis-CI only goes as low as OSX 10.10. (See https://docs.travis-ci.com/user/reference/osx) I guess that is because 10.9 is no longer officially supported by Apple, end-of-life being September 2016, so not receiving security updates anymore. (It is probably not worth supporting by conda either?) 10.10 and 10.11 are still getting security updates, while 10.12 is currently the fully supported version. For the Windows problems, I'll see if I can contribute fixes.

**Comment by tovrstra** [comment] 2017-08-09 07:50
Small update: setting `osx_image: xcode6.4` (OS X 10.10) in `.travis.yml` makes all builds and tests pass on Travis-CI. One down...

**Comment by msarahan** [comment] 2017-08-09 12:31
Your problem on Linux, I believe, goes back to the prefixed executables, but also Python itself.  When Python is built, it stores the compiler information for the compiler that it was built with in the ``_sysconfig.py``.  It *should* be as easy as setting CC to change what it's using down the line, but as I understand it, there are some hard-coded parts of this that suck.  In our latest miniconda, available at https://repo.continuum.io/pkgs/misc/preview/, we build python with our new compilers.  Thus, if you use this miniconda, your errors should go away.

You could also try your install line as:

```CC=${CC} python setup.py install```

and note that because you are using setuptools.setup in your setup.py (as opposed to distutils.setup), your install line should be:

```CC=${CC} python setup.py install --single-version-externally-managed --record=record.txt```

to force setuptools to not create .egg files.

**Comment by msarahan** [comment] 2017-08-09 12:39
PS: numpy also has site.cfg, and because numpy is involved in your recipe, we also need to consider that its compiler setting functionality may also be in play here.

**Comment by tovrstra** [comment] 2017-08-09 12:55
I also think it is due to the compiler used to build Python, distutils copies these settings, so does setuptools. I'm running with `CC=${CC}` now. We don't want eggs in general for our projects because we observed that nosetests cannot find tests inside eggs. Therefore we have the `zip_safe=False` option in our `setup` call. (I still have to report that nose bug. It seems to be a recurring one.)

**Comment by tovrstra** [comment] 2017-08-09 13:03
Sorry, `CC=${CC}`, does not seem to work. I've modified setup.py to write out the essential variables that distutils and setuptools use to determine the compiler:

    ~~~~~~ os.environ ~~~~~~
    CC=None
    ~~~~~~ os.environ ~~~~~~
    ~~~~~~ sysconfig ~~~~~~
    CC=gcc -pthread
    LDSHARED=gcc -pthread -shared -L/home/travis/miniconda/lib -Wl,-rpath=/home/travis/miniconda/lib,--no-as-needed
    CONFIG_ARGS='--enable-shared' '--enable-ipv6' '--enable-unicode=ucs4' '--prefix=/home/travis/miniconda' '--with-tcltk-includes=-I/home/travis/miniconda/include' '--with-tcltk-libs=-L/home/travis/miniconda/lib -ltcl8.5 -ltk8.5' 'CC=gcc' 'LDFLAGS= -L/home/travis/miniconda/lib -Wl,-rpath=/home/travis/miniconda/lib,--no-as-needed' 'CPPFLAGS=-I/home/travis/miniconda/include' 'PKG_CONFIG_PATH=/home/travis/miniconda/lib/pkgconfig'
    ~~~~~~ sysconfig ~~~~~~
    ~~~~~~ distutils.sysconfig ~~~~~~
    CC=gcc -pthread
    LDSHARED=gcc -pthread -shared -L/home/travis/miniconda/lib -Wl,-rpath=/home/travis/miniconda/lib,--no-as-needed
    CONFIG_ARGS='--enable-shared' '--enable-ipv6' '--enable-unicode=ucs4' '--prefix=/home/travis/miniconda' '--with-tcltk-includes=-I/home/travis/miniconda/include' '--with-tcltk-libs=-L/home/travis/miniconda/lib -ltcl8.5 -ltk8.5' 'CC=gcc' 'LDFLAGS= -L/home/travis/miniconda/lib -Wl,-rpath=/home/travis/miniconda/lib,--no-as-needed' 'CPPFLAGS=-I/home/travis/miniconda/include' 'PKG_CONFIG_PATH=/home/travis/miniconda/lib/pkgconfig'
    ~~~~~~ distutils.sysconfig ~~~~~~

**Comment by msarahan** [comment] 2017-08-09 13:06
Yeah, so it's that crappy hardcoded stuff jumping ahead of CC as defined by the GCC activate script.  That is really a horrible bug in python/distutils, IMO.  It should always respect any CC env var.  @mingwandroid is there any way around this, other than using the preview miniconda?

**Comment by mingwandroid** [comment] 2017-08-09 13:07
@msarahan, I've never seen this bug on Linux.

Are you using our linux compilers here? Given that you reported:
```
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
```

I assume you must be, because we set that in `CFLAGS` when those packages are activated. Thing is, at the very same time we also set `CC` (see `activate-gcc.sh`).

@msarahan says this shouldn't matter, but can you try moving your build command into a `build.sh` instead? Also, before running setup.py can you run env so we can see the env vars at that time?

**Comment by tovrstra** [comment] 2017-08-09 13:36
This is sad: distutils and setuptools just happily ignore CC:

    ~~~~~~ os.environ ~~~~~~
    CC=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/x86_64-conda_cos6-linux-gnu-cc
    ~~~~~~ os.environ ~~~~~~
    ~~~~~~ sysconfig ~~~~~~
    CC=gcc -pthread
    LDSHARED=gcc -pthread -shared -L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib,--no-as-needed
    CONFIG_ARGS='--enable-shared' '--enable-ipv6' '--enable-unicode=ucs4' '--prefix=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl' '--with-tcltk-includes=-I/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include' '--with-tcltk-libs=-L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -ltcl8.5 -ltk8.5' 'CC=gcc' 'LDFLAGS= -L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib,--no-as-needed' 'CPPFLAGS=-I/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include' 'PKG_CONFIG_PATH=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/pkgconfig'
    ~~~~~~ sysconfig ~~~~~~
    ~~~~~~ distutils.sysconfig ~~~~~~
    CC=gcc -pthread
    LDSHARED=gcc -pthread -shared -L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib,--no-as-needed
    CONFIG_ARGS='--enable-shared' '--enable-ipv6' '--enable-unicode=ucs4' '--prefix=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl' '--with-tcltk-includes=-I/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include' '--with-tcltk-libs=-L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -ltcl8.5 -ltk8.5' 'CC=gcc' 'LDFLAGS= -L/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib,--no-as-needed' 'CPPFLAGS=-I/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include' 'PKG_CONFIG_PATH=/home/travis/miniconda/conda-bld/pycydemo_1502285073957/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/pkgconfig'
    ~~~~~~ distutils.sysconfig ~~~~~~

By the way, should I be worried about all the `_placehold` things?

**Comment by msarahan** [comment] 2017-08-09 14:09
Yes, it's very sad.  I really do not like that behavior.

I have posted the recipes that I pasted in here at https://github.com/AnacondaRecipes/aggregate/pull/2 - that's a better way.

You should not be worried about _placehold.  To learn more, see comments on this issue: https://github.com/conda/conda-build/issues/1337

**Comment by sdrobert** [comment] 2018-01-10 19:44
As of conda 4.4.7, there is a `vs2008_win-{32,64}` package, but no `vs2010_win-{32,64}` packages. This means we can't build for python 3.4.

```
conda search --platform win-64 vs*
Loading channels: done
Name                       Version                   Build  Channel
vs2008_runtime             9.00.30729.1                  0  defaults
vs2008_runtime             9.00.30729.1                  1  defaults
vs2008_runtime             9.00.30729.1                  2  defaults
vs2008_runtime             9.00.30729.1         hfaea7d5_0  defaults
vs2008_runtime             9.00.30729.1         hfaea7d5_1  defaults
vs2008_runtime             9.00.30729.5054               0  defaults
vs2008_win-32              9.00.30729.1         hb7fc0b5_0  defaults
vs2008_win-32              9.00.30729.1         hb7fc0b5_1  defaults
vs2008_win-64              9.00.30729.1         hb7fc0b5_0  defaults
vs2008_win-64              9.00.30729.1         hb7fc0b5_1  defaults
vs2010_runtime             10.00.40219.1                 0  defaults
vs2010_runtime             10.00.40219.1                 1  defaults
vs2010_runtime             10.00.40219.1                 2  defaults
vs2013_runtime             12.0.21005                    1  defaults
vs2015_runtime             14.00.23026.0                 0  defaults
vs2015_runtime             14.0.25123                    0  defaults
vs2015_runtime             14.0.25123           hd4c4e62_1  defaults
vs2015_runtime             14.0.25123           hd4c4e62_2  defaults
vs2015_runtime             14.0.25420                    0  defaults
vs2015_win-32              14.0.25123           hf5d5b87_1  defaults
vs2015_win-32              14.0.25123           hf5d5b87_2  defaults
vs2015_win-64              14.0.25123           hf5d5b87_1  defaults
vs2015_win-64              14.0.25123           hf5d5b87_2  defaults
vs2017_runtime             15.5.2                        0  defaults
vs2017_runtime             15.5.2                        1  defaults
vs2017_win-32              15.5.2                        0  defaults
vs2017_win-32              15.5.2                        1  defaults
vs2017_win-64              15.5.2                        0  defaults
vs2017_win-64              15.5.2                        1  defaults
```

**Comment by msarahan** [comment] 2018-01-10 19:49
@sdrobert it has nothing to do with conda version.  We no longer build packages for python 3.4, and we have thus also dropped support for VS2010.  Actually, it's more accurate to say that we just never supported VS2010 under the new scheme.  The code to support VS2010 without the explicit compiler jinja2 is still there in conda-build.

It would be very easy for you to use/modify the recipe at https://github.com/AnacondaRecipes/aggregate/tree/master/vs2010 and build the packages for yourself.

**Comment by sdrobert** [comment] 2018-01-10 19:53
Ah, no, it's not necessary for me - just thought I'd point it out. Sorry for the bother! Anyway, I suspect you can close this issue.

**Comment by msarahan** [comment] 2018-01-10 19:58
I almost agree with you.  Thanks for raising it.  I haven't yet confirmed that the vs2008_win-* packages work on appveyor with the Compiler for Python 2.7.  It's a finicky, not-quite-visual-studio setup that requires some special casing.  Conda-build has that built-in, and it also requires some CI setup stuff, too.  I need to figure out how to make that work with the new compiler scheme, too.

**Comment by jakirkham** [comment] 2018-06-15 04:04
This is probably ok to close.

**Comment by msarahan** [comment] 2018-06-15 17:47
Thanks, agreed.  I think the new packages are working with appveyor, but if they aren't, please open a new issue.

**Closed by msarahan** 2018-06-15 17:47 UTC

**Comment by marscher** [comment] 2018-06-24 12:50
Could it be possible, that the same applies for the win-64 activation? 
https://ci.appveyor.com/project/marscher/msmtools/build/1.0.231/job/pk0cwlan4y6pf259#L107

Thanks for looking into it!
