### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda-build#625] opened 2015-10-06 15:16 UTC
Dear All,

I am getting the following error while building a new package.

Could you please point to any reason?

Many thanks,
Sebastian.

```
Linking packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):                                                                                                                                                                           |   4%
  File "/Users/sebastian/Desktop/conda/build-1/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/build.py", line 285, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/install.py", line 593, in link
    os.makedirs(dst_dir)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/sebastian/Desktop/conda/build-1/envs/_build_placehold_placehold_placehold/bin'
MRCs-MacBook-Pro-2:cgat-recipes sebastian$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.1
  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/sebastian/Desktop/conda/build-1  (writable)
  default environment : /Users/sebastian/Desktop/conda/build-1
     envs directories : /Users/sebastian/Desktop/conda/build-1/envs
        package cache : /Users/sebastian/Desktop/conda/build-1/pkgs
         channel URLs : https://conda.anaconda.org/cgat/osx-64/
                        https://conda.anaconda.org/cgat/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
          config file : /Users/sebastian/.condarc
    is foreign system : False
```

**Comment by hflamboauto1** [comment] 2016-07-08 15:52
same here

```Traceback (most recent call last):
  File "/opt/conda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 112, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
  File "/opt/conda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 20, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/conda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/opt/conda/lib/python2.7/site-packages/conda/install.py", line 1055, in link
    os.makedirs(dst_dir)
  File "/opt/conda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/conda/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg-info'```

**Comment by msarahan** [comment] 2016-07-08 16:11
Please update conda and try again.  Although you may encounter this problem while using conda-build because it creates environments with conda, the problem is ultimately in conda, not conda-build.  I am moving this issue over there.

**Comment by msarahan** [comment] 2016-07-08 16:11
Issue moved to [conda/conda #3014](https://github.com/conda/conda/issues/3014) via [**ZenHub**](https://www.zenhub.com/)

**Closed by msarahan** 2016-07-08 16:11 UTC
