### ISSUE TITLE
conda skeleton pypi unexpected error

### ISSUE THREAD

**Issue by JBPressac** [conda/conda-build#359] opened 2015-04-03 09:33 UTC
Hello,
I followed [Using PyPi Packages with Conda](http://www.peterbronez.com/Using%20PyPi%20Packages%20with%20Conda) from Peter Bronez in order to install with `conda install` the [django-grappelli](https://pypi.python.org/pypi/django-grappelli/2.6.4) PyPi package. However, the `conda skeleton pypi django-grappelli` command had an unexpected error:

```
C:\Users\ubo>conda skeleton pypi django-grappelli
Warning, the following versions were found for django-grappelli
2.6.4
2.5.7
2.4.12
Using 2.6.4
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/d/django-grappelli/django-grappelli-2.6.4.tar.gz (1.5 MB) for django-grappelli.
Downloading django-grappelli (use --no-download to skip this step)
Using cached download
Unpacking django-grappelli...
done
working in c:\users\ubo\appdata\local\temp\tmpbahncbconda_skeleton_django-grappelli-2.6.4.tar.gz
Fetching package metadata: C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from conf
iguring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
..C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately
 and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
......
Solving package specifications: .
Applying patch: 'c:\\users\\ubo\\appdata\\local\\temp\\tmpbahncbconda_skeleton_django-grappelli-2.6.4.tar.gz\\pypi-distutils.patch'
69 unparsed bytes left at the end of stream
file 1/1:        core.py
 hunk no.1 doesn't match source file at line 165
  expected:
  actual  :                 raise SystemExit, "error: " + str(msg)
source file is different - core.py
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 188, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 321, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 202, in execute
    pypi.main(args, parser)
  File "C:\Miniconda\lib\site-packages\conda_build\pypi.py", line 376, in main
    get_package_metadata(args, package, d, data)
  File "C:\Miniconda\lib\site-packages\conda_build\pypi.py", line 432, in get_package_metadata
    run_setuppy(src_dir, tempdir, args)
  File "C:\Miniconda\lib\site-packages\conda_build\pypi.py", line 690, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 235, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "C:\Miniconda\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Miniconda\\Scripts\\patch.bat', '-p0', '-i', 'c:\\users\\ubo\\appdata\\local\\temp\\tmpbahncbconda_skeleton_django-grappelli-2.6.4.tar.gz\\pypi-distutils.
patch']' returned non-zero exit status -1
```
My `conda info`:

```
[django] C:\Users\ubo>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Miniconda  (writable)
  default environment : C:\Miniconda\envs\django
     envs directories : C:\Miniconda\envs
        package cache : C:\Miniconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.binstar.org/JBPressac/win-64/
                        https://conda.binstar.org/JBPressac/noarch/
          config file : C:\Users\ubo\.condarc
    is foreign system : False
```

Thanks,

**Comment by asmeurer** [comment] 2015-04-06 20:46
This looks like a duplicate of https://github.com/conda/conda-build/issues/119.

**Closed by asmeurer** 2015-04-06 20:46 UTC
