### ISSUE TITLE
Error when running conda build in Python 3

### ISSUE THREAD

**Issue by astrofrog** [conda/conda-build#944] opened 2016-05-12 10:49 UTC
I tried running conda build (in Python 3) for the following recipe:

https://github.com/astrofrog/staged-recipes/tree/7b737db02bfe704623ac1391f8176795c7fd64d0/recipes/glueviz

and ran into the following error

```
...
updating shebang: bin/glue
b"#!/bin/bash /Users/tom/miniconda3/envs/_build/bin/python.app\n# EASY-INSTALL-ENTRY-SCRIPT: 'glueviz==0.7.3','gui_scripts','glue'\n__requires__ = 'glueviz==0.7.3'\nimport sys\nfrom pkg_resources import load_entry_point\n\nif __name__ == '__main__':\n    sys.exit(\n        load_entry_point('glueviz==0.7.3', 'gui_scripts', 'glue')()\n    )\n"
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/tom/miniconda3/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 208, in main
    args_func(args, p)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 438, in execute
    include_recipe=args.include_recipe)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 515, in build
    post_build(m, sorted(files2 - files1))
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 333, in post_build
    fix_shebang(f, osx_is_app=osx_is_app)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 77, in fix_shebang
    fo.write(new_data)
TypeError: write() argument must be str, not bytes
```

**Comment by frol** [comment] 2016-05-12 19:00
It is a duplicate of #889.

**Closed** 2018-11-05 09:55 UTC
