### ISSUE TITLE
Cannot specify exact match of package in meta.yaml

### ISSUE THREAD

**Issue by kpurdon** [conda/conda-build#414] opened 2015-05-19 16:13 UTC
I would like to be able to specify (in the meta.yaml) an EXACT match of package.

For example I want two packages: `gdal` and `proj4`, right now I can specify:

```
- gdal ==1.11.2
- proj4
```

It will not find `proj4' in defaults so I add the `osgeo` channel to my .condarc. However, I want gdal 1.11.2 from defaults and proj4 from osgeo. Ideally I could do something like:

```
- gdal ==1.11.2 [defaults]
- proj4 [osgeo]
```

Which would allow my to now fully specify the exact version and channel from which my package should come.

**Comment by asmeurer** [comment] 2015-05-19 16:14
This is a duplicate of https://github.com/conda/conda/issues/988

**Closed by asmeurer** 2015-05-19 16:14 UTC
