### ISSUE TITLE
`source` lists do not allow `path` in conda-build 3.28.x

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-build#5111] opened 2023-12-12 12:42 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Seen in https://github.com/conda/conda-standalone/pull/36.

This type of `source` metadata:

```
source:
  - path: ../

  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 9276686c8a6ee536dc451cc6557685724fe275a44949ac4f741066fd23cdc7b4
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - ../src/conda_patches/0003-Return-unknown-module-in-deprecations.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 787ffd85e9414bdf70fe531f01eab3987a040e3f6a6ac3a01409f4d332f7de9e  # [win]
    folder: constructor_src  # [win]
```

results in this traceback:

```
WARNING: No index specified in get_value('source/path'). Assuming index 0.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 140, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 572, in execute
        outputs = api.build(
                  ^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/api.py", line 2[54](https://github.com/conda/conda-standalone/actions/runs/7181452098/job/19555878864#step:5:55), in build
        return build_tree(
               ^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/build.py", line 3793, in build_tree
        packages_from_this = build(
                             ^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/build.py", line 2474, in build
        output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/render.py", line 929, in expand_outputs
        for output_dict, m in deepcopy(_m).get_output_metadata_set(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/metadata.py", line 2[58](https://github.com/conda/conda-standalone/actions/runs/7181452098/job/19555878864#step:5:59)6, in get_output_metadata_set
        conda_packages = finalize_outputs_pass(
                         ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/metadata.py", line 949, in finalize_outputs_pass
        fm = finalize_metadata(
             ^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.11/site-packages/conda_build/render.py", line [72](https://github.com/conda/conda-standalone/actions/runs/7181452098/job/19555878864#step:5:73)6, in finalize_metadata
        m.meta["source"]["path"] = normpath(join(m.path, source_path))
        ~~~~~~~~~~~~~~~~^^^^^^^^
    TypeError: list indices must be integers or slices, not str
```

Reverting to conda-build=3.27 fixes the issue.

### Conda Info

```shell
active environment : base
    active env location : /usr/share/miniconda
            shell level : 1
       user config file : /home/runner/.condarc
 populated config files : /home/runner/.condarc
          conda version : 23.10.0
    conda-build version : 3.28.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=zen2
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.5 Linux/6.2.0-1018-azure ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 1001:127
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
See https://github.com/conda/conda-standalone/actions/runs/7181452098/job/19555878864
```

**Comment by kenodegard** [comment] 2023-12-12 14:49
This is caused by the `MetaData` `get_section`/`get_value` refactor #5055.

**Before:**
https://github.com/conda/conda-build/blob/923b59aa791e6b97691037d460be479317923104/conda_build/render.py#L710-L727

**After:**
https://github.com/conda/conda-build/blob/decbcf9dd6250dca251e195790b8fb81ec0c5fe9/conda_build/render.py#L724-L734

Before we were testing to see if `path` was defined in `source` and since the conda-standalone recipe defines several sources it is a `list` (instead of a single `dict`) and the `"path" in m.meta["source"]` conditional would always return false and the code block was previously skipped.

**Comment by kenodegard** [comment] 2023-12-18 15:28
#5112 has been merged, patch release coming this week

**Closed by kenodegard** 2023-12-18 15:28 UTC
Labels: type::bug, source::contributor
