### ISSUE TITLE
"conda pipbuild seaborn" fails to install

### ISSUE THREAD

**Issue by wikiped** [conda/conda-build#229] opened 2014-10-21 22:43 UTC
It does look like other errors with pipbuild that have the same "ending":

    File "D:\Anaconda\lib\subprocess.py", line 958, in _execute_child
		startupinfo)
	WindowsError: [Error 2] The system cannot find the file specified

however it deviates at:

    File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 245, in make_rec
	ipe 

Full output:

	D:\>activate py2k
	Activating environment "py2k"...

	[py2k] D:\>conda pipbuild seaborn
	Fetching package metadata: ...
	Creating standard recipe for seaborn-0.4.0
	Using url https://pypi.python.org/packages/source/s/seaborn/seaborn-0.4.0.tar.gz (85 KB) f
	or seaborn.
	Downloading seaborn (use --no-download to skip this step)
	Using cached download
	Unpacking seaborn...
	done
	working in c:\users\Named\appdata\local\temp\tmpz6cwpdconda_skeleton_seaborn
	Fetching package metadata: ....
	Solving package specifications: .69 unparsed bytes left at the end of stream
	file 1/1:        core.py
	 hunk no.1 doesn't match source file at line 165
	  expected:
	  actual  :                 raise SystemExit, "error: " + str(msg)
	source file is different - core.py

	Applying patch: 'c:\\users\\Named\\appdata\\local\\temp\\tmpz6cwpdconda_skeleton_seaborn\
	\pypi-distutils.patch'
	An unexpected error has occurred, please consider sending the
	following traceback to the conda GitHub issue tracker at:

		https://github.com/conda/conda-build/issues

	Include the output of the command 'conda info' in your report.

	Traceback (most recent call last):
	  File "D:\Anaconda\Scripts\conda-skeleton-script.py", line 4, in <module>
		sys.exit(main())
	  File "D:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 131, in main
		args_func(args, p)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in args_func
		args.func(args, p)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 142, in execute
		pypi.main(args, parser)
	  File "D:\Anaconda\lib\site-packages\conda_build\pypi.py", line 407, in main
		run_setuppy(src_dir, tempdir, args)
	  File "D:\Anaconda\lib\site-packages\conda_build\pypi.py", line 596, in run_setuppy
		apply_patch(join(stdlib_dir, 'distutils'), patch)
	  File "D:\Anaconda\lib\site-packages\conda_build\source.py", line 209, in apply_patch
		check_call([patch, '-p0', '-i', path], cwd=src_dir)
	  File "D:\Anaconda\lib\subprocess.py", line 540, in check_call
		raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '['D:\\Anaconda\\Scripts\\patch.bat', '-p0', '-i',
	'c:\\users\\Named\\appdata\\local\\temp\\tmpz6cwpdconda_skeleton_seaborn\\pypi-distutils.
	patch']' returned non-zero exit status -1

	conda create -n _pipbuild_ --yes python pip
	Error: prefix already exists: D:\Anaconda\envs\_pipbuild_
	D:\Anaconda\envs\py2k\envs\_pipbuild_/bin/pip install seaborn==0.4.0
	An unexpected error has occurred, please consider sending the
	following traceback to the conda GitHub issue tracker at:

		https://github.com/conda/conda-build/issues

	Include the output of the command 'conda info' in your report.

	Traceback (most recent call last):
	  File "D:\Anaconda\Scripts\conda-pipbuild-script.py", line 4, in <module>
		sys.exit(main())
	  File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 77, in main
		args_func(args, p)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in args_func
		args.func(args, p)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 350, in execute
		build_package(package, version)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 303, in build_pa
	ckage
		directory, dependencies = make_recipe(package, version)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 245, in make_rec
	ipe
		depends = get_all_dependencies(package, version)
	  File "D:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 215, in get_all_
	dependencies
		ret = subprocess.Popen(cmd2.split()).wait()
	  File "D:\Anaconda\lib\subprocess.py", line 710, in __init__
		errread, errwrite)
	  File "D:\Anaconda\lib\subprocess.py", line 958, in _execute_child
		startupinfo)
	WindowsError: [Error 2] The system cannot find the file specified

	[py2k] D:\>conda info
	Current conda install:

				 platform : win-64
			conda version : 3.7.1
	  conda-build version : 1.8.2
		   python version : 2.7.8.final.0
		 requests version : 2.4.3
		 root environment : D:\Anaconda  (writable)
	  default environment : D:\Anaconda\envs\py2k
		 envs directories : D:\Anaconda\envs
			package cache : D:\Anaconda\pkgs
			 channel URLs : http://repo.continuum.io/pkgs/free/win-64/
							http://repo.continuum.io/pkgs/pro/win-64/
							https://conda.binstar.org/Primer/win-64/
			  config file : C:\Users\Named\.condarc
		is foreign system : False

**Comment by remram44** [comment] 2016-01-02 18:06
Duplicate of #119, should be fixed.

**Comment by msarahan** [comment] 2016-01-02 18:26
Thanks @remram44 closing. Please reopen or post new issue if you still have problems here.

**Closed by msarahan** 2016-01-02 18:26 UTC
