### ISSUE TITLE
ImportError: No module named 'conda.base'

### ISSUE THREAD

**Issue by postelrich** [conda/conda-build#1531] opened 2016-11-14 17:21 UTC
Get the following error on conda-build 2.0.9.  Reverted to 2.0.8 and have no issues.

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-build", line 4, in <module>
    import conda_build.cli.main_build
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 16, in <module>
    import conda_build.api as api
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import string_types, binstar_upload
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/conda_interface.py", line 27, in <module>
    from conda.base.constants import SEARCH_PATH
ImportError: No module named 'conda.base'

PATH="$MINICONDA_PATH:$PATH" $CONDA build conda-recipe -c creditflow returned exit code 1
```

**Comment by msarahan** [comment] 2016-11-14 17:23
Thanks for the report.  This is a duplicate of #1527 and #1530.  It is fixed by #1528, which is part of 2.0.10.  That has been tagged, but may not yet be available as a package.

**Closed by msarahan** 2016-11-14 17:23 UTC
