### ISSUE TITLE
Built package try to downgrade python and xz.

### ISSUE THREAD

**Issue by starhel** [conda/conda-build#1602] opened 2016-12-23 02:45 UTC
Hey guys. I've created my own package with sqlite using new, clean miniconda + conda-build. When I've tried to install package, it tried to downgrade python anx xz. It's my first package and I have no idea what I'm doing wrong (or it's a bug?). 

Some info to make it more clear:
> meta.yml
```
package:
  name: sqlite
  version: 3.15.2

source:
  fn: sqlite-autoconf-3150200.tar.gz
  url: https://www.sqlite.org/2016/sqlite-autoconf-3150200.tar.gz
  sha1: 31f52169bcfeef9efb61480d0950e928ad059552

test:
  commands:
    - sqlite3 --version
```
> conda install --use-local sqlite --dry-run
```
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/adrian/tmp/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.5.1               |                0        16.7 MB

The following packages will be UPDATED:

    sqlite: 3.13.0-0 --> 3.15.2-0 local

The following packages will be DOWNGRADED due to dependency conflicts:

    python: 3.5.2-0  --> 3.5.1-0       
    xz:     5.2.2-0  --> 5.0.5-1
```
> conda info
```
               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/adrian/tmp/conda  (writable)
    default environment : /home/adrian/tmp/conda
       envs directories : /home/adrian/tmp/conda/envs
          package cache : /home/adrian/tmp/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```
> conda list
```
conda                     4.2.13                   py35_0  
conda-build               2.0.12                   py35_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py35_0  
filelock                  2.0.7                    py35_0  
jinja2                    2.8                      py35_1  
markupsafe                0.23                     py35_2  
openssl                   1.0.2j                        0  
patchelf                  0.9                           0  
pip                       8.1.2                    py35_0  
pkginfo                   1.4.1                    py35_0  
pycosat                   0.6.1                    py35_1  
pycrypto                  2.6.1                    py35_4  
python                    3.5.2                         0  
pyyaml                    3.12                     py35_0  
readline                  6.2                           2  
requests                  2.11.1                   py35_0  
ruamel_yaml               0.11.14                  py35_0  
setuptools                27.2.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3 
```

**Comment by msarahan** [comment] 2016-12-23 03:58
Conda is based on constraints and mathematical solution of those constraints (with something called a SAT solver.)

Long story short: Stuff depends on particular versions of stuff.  Python depends on a particular version of sqlite.  That expression is manually set to the best of someone's knowledge of what version of a library will be compatible with what they've built.  If you want to update some underpinning library, you might end up needing to rebuild part or all of the whole stack.  The downgrades are happening because there's an older version of Python that does not have constraints, or has less strict constraints set.  This is sometimes fine - sometimes things will just work, in which case the constraint set was unnecessarily tight.  The only way to know is to relax the constraints yourself and test it.  By relax constraints, I mean edit the recipe for the thing you want (in this case, probably Python).  Then you need to rebuild the package.  However, if you want libraries updated, it is perhaps best to achieve this with PRs to Conda-forge recipes.  Search for python-feedstock, sqlite-feedstock, etc.  Note that different versions are in different branches.

Closing, as this is not a bug in conda-build.

**Closed by msarahan** 2016-12-23 03:58 UTC
