### ISSUE TITLE
Conda-build 3.10.4 - Building R packages

### ISSUE THREAD

**Issue by slacalle** [conda/conda-build#2913] opened 2018-05-23 16:57 UTC
An R package recipe that had worked up to conda-build 3.10.3 is no longer working. I have tried creating new recipes with CRAN and end up with the same error.
The recipe in question is this one: [https://github.com/conda-forge/r-mice-feedstock/](url)

During the last tests, it fails as it cannot find the R binary. It looks like it is searching in the wrong location and not in the test environment and ends up with something like:

`+ ~/anaconda3/envs/build_condaforge/conda-bld/r-mice_1527094155372/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/R -e 'library('\''mice'\'')'
~/anaconda3/envs/build_condaforge/conda-bld/r-mice_1527094155372/test_tmp/run_test.sh: line 7: ~/anaconda3/envs/build_condaforge/conda-bld/r-mice_1527094155372/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/R: No such file or directory
Tests failed for r-mice-2.46.0-r341hf484d3e_0.tar.bz2 - moving package to ~/anaconda3/envs/build_condaforge/conda-bld/broken
WARNING:conda_build.build:Tests failed for r-mice-2.46.0-r341hf484d3e_0.tar.bz2 - moving package to ~/anaconda3/envs/build_condaforge/conda-bld/broken`

**Comment by msarahan** [comment] 2018-05-23 17:03
duplicate of #2901; fixed by #2910

**Closed by msarahan** 2018-05-23 17:03 UTC

**Comment by slacalle** [comment] 2018-05-23 17:06
Ah, I did not see it, my apologies. Thank you for the prompt respond Mike!

**Comment by msarahan** [comment] 2018-05-23 17:07
No worries.  Searching through issues is pretty abysmal.
