### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by agmills7** [conda/conda-build#1066] opened 2016-06-28 22:30 UTC
Ran into this when running conda build. I tried running Git Bash as an administrator and still hit the same thing.

Extracting packages ...
An unexpected error has occurred, please consider sending the            |  14%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Anthony\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 144, in main
    args_func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 389, in args_func
    args.func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 332, in execute
    dirty=args.dirty, activate=args.activate)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\build.py", line 494, in build
    create_env(config.build_prefix, specs)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\build.py", line 367, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Anthony\\Anaconda3\\pkgs\\requests-2.10.0-py35_0.tmp' -> 'C:\\Users\\Anthony\\Anaconda3\\pkgs\\requests-2.10.0-py35_0'

Anthony@M1768954 MINGW64 ~/Anaconda3/RECEPIESRDKIT/conda-rdkit-master
$ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Anthony\Anaconda3  (writable)
  default environment : C:\Users\Anthony\Anaconda3
     envs directories : C:\Users\Anthony\Anaconda3\envs
        package cache : C:\Users\Anthony\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by msarahan** [comment] 2016-06-28 23:05
CC @mcg1969 - this has been a very elusive error.  Anything we can do to reproduce this will be extremely helpful.

**Comment by mcg1969** [comment] 2016-06-28 23:15
I _think_ this is the one I just fixed for 4.1.5 and 4.0.11.

**Comment by kalefranz** [comment] 2016-06-28 23:26
Actually haven't released 4.0.10 yet, so wi l

**Comment by agmills7** [comment] 2016-06-30 19:32
I just tried to update to 4.1.5 using conda update conda and I got the same error:

Traceback (most recent call last):
  File "C:\Users\Anthony\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Anthony\\Anaconda3\\pkgs\\conda-4.1.5-py35_0.tmp' -> 'C:\\Users\\Anthony\\Anaconda3\\pkgs\\conda-4.1.5-py35_0'

**Comment by mcg1969** [comment] 2016-06-30 20:08
@agmills7 do you know if the directory `C:\Users\Anthony\Anaconda3\pkgs\conda-4.1.5-py35_0.tmp` currently exists?

**Comment by agmills7** [comment] 2016-06-30 22:11
Yes, it looks like it does.

**Comment by mcg1969** [comment] 2016-06-30 22:18
OK, one more thing: are you running a virus scanner?

**Comment by mcg1969** [comment] 2016-06-30 22:18
We _just today_ discovered that virus scanners cause some of the issues like these.

**Comment by agmills7** [comment] 2016-06-30 22:19
Yes, I'm running McAfee. I'll turn it off and run it again.

**Comment by agmills7** [comment] 2016-06-30 22:28
Turning off the virus scanner let me successfully run conda update conda.
I'll see again if I can run conda-build and let you know.

Thanks for the help.

**Comment by mcg1969** [comment] 2016-06-30 22:35
This looks to be the exact issue we identied this afternoon. We are working on a fix that will allow conda to work even with the virus scanner on, but in the meanwhile, try turning it off temporarily should help.

The funny thing is, once we identified the source of the problem (the virus scanner), we did some googling and found a wealth of information. But until you know the cause, there's not much to Google!

**Comment by mingwandroid** [comment] 2016-06-30 22:54
Well, my `exp_backoff_fn` commit explicitly called them out, but yes, there's obviously even more call-sites.

**Comment by mcg1969** [comment] 2016-06-30 23:03
Good point, @mingwandroid!

**Comment by mcg1969** [comment] 2016-06-30 23:12
In fact, the real problem seems to have been we were not willing to use it as aggressively (e.g., with sufficiently long delays) as we should have.

**Comment by kalefranz** [comment] 2016-06-30 23:17
Speaking of call sites, my project structure PR will let us isolate all of this in one disk IO location.

**Comment by kalefranz** [comment] 2016-06-30 23:17
Oh this in conda-build. Still...

**Comment by msarahan** [comment] 2016-07-06 18:58
Closing this as a conda-build issue - this is a conda problem.  I hope it's fixed or close to fixed.  Issue over there is https://github.com/conda/conda/issues/2079 - among many others.

**Closed by msarahan** 2016-07-06 18:58 UTC
