### ISSUE TITLE
conda build skips all build steps

### ISSUE THREAD

**Issue by pmlandwehr** [conda/conda-build#1032] opened 2016-06-16 00:34 UTC
Recipe zip at [ggplot.zip,](https://github.com/conda/conda-build/files/317441/ggplot.zip) but here's the key snippet:

```
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

  run:
    - python
    - brewer2mpl
    - matplotlib
    - pandas
    - patsy >=0.4
    - scipy
    - statsmodels

test:
  imports:
    - ggplot
```

when run, I get this:

```
azuolas:recipes pmlandwehr$ conda build ggplot
Removing old build environment
BUILD START: ggplot-0.9.4-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................
Solving package specifications .......
TEST START: ggplot-0.9.4-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................
Solving package specifications ....
Error: Package missing in current osx-64 channels: 
  - ggplot 0.9.4 py35_0
azuolas:recipes pmlandwehr$ 
```

**Comment by pmlandwehr** [comment] 2016-06-16 04:13
(I will add that this same recipe sometimes builds correctly, so I assume that something causing the build to be skipped is occurring silently in the background.)

**Comment by msarahan** [comment] 2016-06-16 18:05
for the sake of reproducing this, what version of conda-build are you using?

**Comment by pmlandwehr** [comment] 2016-06-16 21:43
conda-build 1.21.0

**Comment by pmlandwehr** [comment] 2016-06-16 21:55
Identical issue with a recipe for elasticsearch ([zip](https://github.com/conda/conda-build/files/319393/elasticsearch.zip)). Here's the relevant section:
```
requirements:
  build:
    - python
    - setuptools
    - urllib3 >=1.8,<2.0

  run:
    - python
    - urllib3 >=1.8,<2.0

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.connection
    - elasticsearch.helpers

  requires:
    - coverage
    - mock
    - nose
    - nosexcover
    - pyaml
    - requests >=1.0.0,<3.0.0
```

And here's the output:
```
azuolas:recipes pmlandwehr$ conda  build elasticsearch/
Removing old build environment
BUILD START: elasticsearch-2.3.0-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................
Solving package specifications .......
TEST START: elasticsearch-2.3.0-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................
Solving package specifications ....
Error: Package missing in current osx-64 channels: 
  - elasticsearch 2.3.0 py35_0
azuolas:recipes pmlandwehr$
```

**Comment by msarahan** [comment] 2016-06-22 20:33
I have tested this with conda-build 1.21.1, and ggplot seems to be working.  elasticsearch is missing a urllib3 dependency.  Please try with 1.21.1 and let me know if you still have problems.  This may have been related to some dumb activation bugs.

**Comment by mpharrigan** [comment] 2016-06-23 17:05
I'm seeing the same behavior with a recipe on windows only (locally and appveyor). The recipe works fine on linux (locally and travis ci).

I've upgraded to conda-build 1.21.1 and the problem persists

**Comment by msarahan** [comment] 2016-06-23 17:26
Thanks, can you point me to your recipe, so I can try to duplicate it?

**Comment by mpharrigan** [comment] 2016-06-23 18:05
link: https://github.com/msmbuilder/msmbuilder/blob/master/devtools/conda-recipe/meta.yaml

```yaml
package:
  name: msmbuilder-dev
  version: "0.0.0"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main


requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc


test:
  requires:
    - nose
    - nose-timer
    - munkres
    - numdifftools
    - statsmodels
    - hmmlearn
    - cvxpy # [not win]
  imports:
    - msmbuilder
  commands:
    - msmb -h
    - nosetests msmbuilder -v --with-timer


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
```

**Comment by mpharrigan** [comment] 2016-06-23 18:08
Update: it works with everything except
`conda build --numpy 1.11`
or
`conda build --numpy 111`

where I see the behavior that it skips all build steps

**Comment by msarahan** [comment] 2016-06-23 18:13
Thanks.  Are there any particular versions of python associated, or are all of them broken?

**Comment by mpharrigan** [comment] 2016-06-23 18:28
From an up-to-date python 3.5 32-bit root environment (still windows), I see the problem as well

**Comment by msarahan** [comment] 2016-06-23 18:31
thanks, I am able to reproduce.  I will fix this for the next release, coming ASAP.

**Comment by msarahan** [comment] 2016-06-23 23:18
OK, here's the deal.  It's not a conda-build bug.  It's a dependency resolution issue that conda-build does not expose appropriately.

Ultimately, the problem is that pytables (which is an indirect dependency, through mdtraj) does not have a np111 build.  This causes the _build environment to be unsatisfiable, but conda-build does not quit with any kind of error - just drops out.  I'll see about adding better messaging, but ultimately, we're dependent on conda's ability to provide helpful hints.  In this case, conda's "helpful" hint was that python 2.7 was unsatisfiable.  Since the other dependencies were very vanilla, I looked at mdtraj.

**Comment by mpharrigan** [comment] 2016-06-23 23:22
I think a better error message would actually be really helpful here :+1:

**Comment by msarahan** [comment] 2016-06-24 02:55
Added here: https://github.com/conda/conda-build/pull/1046/commits/62ecffdefa2215a2cf77a44e44f1aa0c98844989

Closing - but I'll reopen this issue if further reports come in.

**Closed by msarahan** 2016-06-24 02:55 UTC
