### ISSUE TITLE
"--python=all" and multiple "--python=x.y" failing

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1557] opened 2016-11-29 10:26 UTC
Using the `--python=all` or, e.g., `--python=3.5 --python=3.6` options results in a `ValueError` in conda build. `conda build --help` states that both should be possible:
```bash
$ conda build --python=all conda/
Traceback (most recent call last):
  File "/localhome/stefan/emsconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 244, in main
    execute(sys.argv[1:])
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 197, in execute
    config = Config(**args.__dict__)
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/config.py", line 47, in __init__
    self.set_keys(**kwargs)
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/config.py", line 72, in set_keys
    .replace('.', ''))
ValueError: invalid literal for int() with base 10: 'all'
```
```bash
$ conda build --python=3.5 --python=3.6 conda/
Traceback (most recent call last):
  File "/localhome/stefan/emsconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 244, in main
    execute(sys.argv[1:])
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 197, in execute
    config = Config(**args.__dict__)
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/config.py", line 47, in __init__
    self.set_keys(**kwargs)
  File "/localhome/stefan/emsconda/lib/python3.5/site-packages/conda_build/config.py", line 71, in set_keys
    self.CONDA_PY = int(env('python', "%s%s" % (sys.version_info.major, sys.version_info.minor))
AttributeError: 'list' object has no attribute 'replace'
```
```bash
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.11
         python version : 3.5.2.final.0
       requests version : 2.11.1
...
           offline mode : False
```

**Comment by msarahan** [comment] 2016-11-29 13:51
Duplicate of #1316.  This functionality was broken in the Conda-build 2 refactor.  I don't think it's coming back.  It is my opinion that conda-build is not built to be a matrix build tool (right now.)  #1142 may change that.

For now, I recommend using conda-build-all instead: https://github.com/SciTools/conda-build-all

**Closed by msarahan** 2016-11-29 13:51 UTC
