### ISSUE TITLE
Problem: --skip existing doesnt work anymore

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1604] opened 2016-12-23 11:58 UTC
In latest master --skip-existing does not skip packes that are available in remote repositories anymore

**Comment by msarahan** [comment] 2016-12-23 15:58
Can you please post more information?  There are tests for this functionality, so I'd like to understand how it isn't working for you.  

https://github.com/conda/conda-build/blob/master/tests/test_api_build.py#L332-L361

**Comment by gabm** [comment] 2016-12-23 18:41
I can check the tests next week..

in my usecase i have a number of folders that contain recipes and a remote repository that contains packages.

i run the script on all folders under Linux and it doesn't skip existing packages. Downgrading to the last stable makes it skip packages as wanted. The same happens if I only give exactly one recipe and no other options except for "skip-existing". it seems to me that it's broken totally since i updated to the master today from the last stable...

**Comment by msarahan** [comment] 2016-12-23 18:50
Please post a recipe and set of build commands that reproduce the issue, if
you can. Also, please post the output of conda info.

**Comment by gabm** [comment] 2016-12-23 19:10
well i can't upload anything unfortunately, but I'll have to investigate that definitely..  I'll give you feedback on Tuesday. Until then: happy Christmas ;)

**Comment by gabm** [comment] 2016-12-27 09:10
ok, I narrowed it down. The test fails for me as well.

The problem is the interface between conda and conda-build that changed. Just to clarify, I'm using the following versions:
- conda: 4.3.2 - latest master @3d74644ffc0a57cd49b3429de9751243794f891e
- conda-build: 2.1.0beta1 - latest master @327d9a358e2b849a05e1cd33bb5f917dd96b9bb8

I found out that the problem does not change, when downgrading conda-build but *does* change when downgrading conda to 4.2.13. So I went my way through the source code until conda_interface `get_index`.

If conda is in version 4.2.13 it delivers a python dictionary of the form:

```
{ <canonical_name>:
   features: ...
   url: ...
   depends: ..
...
}
```

In conda 4.3.1 (latest master) however, we get something like this:

```
{ 
Dist(
  _Dist__initd=True,
  channel='[..]', 
  dist_name='conda-4.2.13.dev1+d929a51-py35_0', 
  name='conda', version='4.2.13.dev1+d929a51', 
  build_string='py35_0', 
  build_number=0, 
  with_features_depends=None, 
  base_url='[..]', 
  platform='linux-64'): 
    IndexRecord(
      _IndexRecord__initd=True, 
      build='py35_0', 
      build_number=0, 
      depends=('pycosat >=0.6.1', 'python 3.5*', 'requests >=2.5.3', 'ruamel_yaml >=0.11.7'), l
      icense='BSD', 
      md5='dd407b292fbce59cb11402c0771a7944', 
      name='conda', 
      size=407323, 
      subdir='linux-64', 
      version='4.2.13.dev1+d929a51', 
      n='conda-4.2.13.dev1+d929a51-py35_0.tar.bz2', 
      schannel='[..]', 
      channel='[..]/linux-64', 
      priority=1, url='[..]/linux-64/conda-4.2.13.dev1+d929a51-py35_0.tar.bz2',
      auth=None)
}
```

Now of course the simple check in `is_package_built` (https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1586) fails..

So the API of conda changed and conda-build is not prepared for that.

**Comment by msarahan** [comment] 2016-12-28 18:10
Thanks for isolating this issue.  Conda 4.3 support is indeed lacking.

@kalefranz how do you want to handle this?  I'd obviously prefer if Conda didn't break Conda-build, mostly because I don't know which other projects might also be broken by this change.  At one point, you mentioned possibly implementing a ```__str___``` method for the Dist class.  Is that still an option?  Since it seems like this is expecting more of a dictionary interface, perhaps we want ```__getitem__``` instead?

CC @csoja

**Comment by gabm** [comment] 2016-12-29 17:00
I think that *a workaround* (like overloading `__str__`) is not very helpful.

What conda needs is a clearly defined API to its internal functions that can be used by client programs. I see some code replication through the different projects (conda-build, conda-verify, constructor and possibly others) and some undefined access to internal data structures (like in conda-build). There will be no warning, before it breaks next time...

**Comment by jhunkeler** [comment] 2017-01-18 13:18
Hi, has there been any further development on this? The latest version (`conda-build 2.1.1` | `conda 4.3.4`) still shows this behavior. On 01/14/2017 or so my daily packages builds started rebuilding themselves even with `--skip-existing` enabled.

I thought it was just me... but apparently I was wrong ;)

**Comment by msarahan** [comment] 2017-01-18 13:27
Progress is at #1667 - it fixes skip-existing, but things are not quite ready to go yet.  The failing tests are passing locally when run in isolation, but failing when run with the rest of the test suite.  Hopefully we can get to the bottom of it today.

**Comment by jhunkeler** [comment] 2017-01-18 13:31
@msarahan Thanks for the update. Good luck!

**Comment by msarahan** [comment] 2017-02-24 20:32
I think this is fixed with latest conda-build releases.  Closing - please reopen if this is still an issue.

**Closed by msarahan** 2017-02-24 20:32 UTC
