### ISSUE TITLE
conda skeleton pypi - "--python-version" has no effect

### ISSUE THREAD

**Issue by blankclemens** [conda/conda-build#1403] opened 2016-09-27 14:53 UTC
`conda skeleton pypi` will always use Python 3.5, trying to build Python 2 packages fails therefore (missing parentheses most of the time). Conda is from Miniconda 3, running on Ubuntu 16.04.

Example call (as you can see it tries to install Python 3.5):

```
conda skeleton pypi --python-version 2.7 pyquant-ms

Warning, the following versions were found for pyquant-ms
0.1.0
0.1.1
0.1.2
0.1.31
0.1.32
0.1.33
0.1.34
0.1.35
0.1.36
0.1.37
0.1.38
0.1.39
0.1.40
0.1.41
0.1.42
Using 0.1.42
Use --version to specify a different version.
Using url https://pypi.python.org/packages/9f/70/b7f8f6b0cbf381d544dda6daf949a4704037a19b7fe1386a1edbea613c04/pyquant-ms-0.1.42.tar.gz (861 KB) for pyquant-ms.
Downloading pyquant-ms
Using cached download
Unpacking pyquant-ms...
done
working in /tmp/tmp7c56qgb0conda_skeleton_pyquant-ms-0.1.42.tar.gz

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2016.8.31-0                   conda-forge
    certifi:         2016.8.31-py35_0              conda-forge
    libgfortran:     3.0.0-1                                  
    ncurses:         5.9-9                         conda-forge
    numpy:           1.11.1-py35_blas_openblas_201 conda-forge [blas_openblas]
    openblas:        0.2.18-5                      conda-forge
    openssl:         1.0.2h-2                      conda-forge
    pip:             8.1.2-py35_0                  conda-forge
    python:          3.5.2-2                       conda-forge
    pyyaml:          3.11-py35_0                   conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      26.1.1-py35_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-0                      conda-forge
    wheel:           0.29.0-py35_0                 conda-forge
    xz:              5.2.2-0                       conda-forge
    yaml:            0.1.6-0                       conda-forge
    zlib:            1.2.8-3                       conda-forge


The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2016.8.31-0                   conda-forge
    certifi:         2016.8.31-py35_0              conda-forge
    libgfortran:     3.0.0-1                                  
    ncurses:         5.9-9                         conda-forge
    numpy:           1.11.1-py35_blas_openblas_201 conda-forge [blas_openblas]
    openblas:        0.2.18-5                      conda-forge
    openssl:         1.0.2h-2                      conda-forge
    pip:             8.1.2-py35_0                  conda-forge
    python:          3.5.2-2                       conda-forge
    pyyaml:          3.11-py35_0                   conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      26.1.1-py35_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-0                      conda-forge
    wheel:           0.29.0-py35_0                 conda-forge
    xz:              5.2.2-0                       conda-forge
    yaml:            0.1.6-0                       conda-forge
    zlib:            1.2.8-3                       conda-forge

Applying patch: '/tmp/tmp7c56qgb0conda_skeleton_pyquant-ms-0.1.42.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
  File "setup.py", line 10
    print 'CYTHON UNAVAILABLE'
                             ^
SyntaxError: Missing parentheses in call to 'print'
$PYTHONPATH = /tmp/tmp7c56qgb0conda_skeleton_pyquant-ms-0.1.42.tar.gz/pyquant-ms-0.1.42
Error: command failed: /home/clemens/miniconda3/conda-bld/skeleton_1474987867403/_b_env_placehold_place/bin/python setup.py install
```

Since conda build is not installed in a virtual environment, I don't know if there is an easy way to check if it's an error with my setup.

**Comment by msarahan** [comment] 2016-09-27 15:12
Thanks for the detailed report.  This is a duplicate of https://github.com/conda/conda-build/issues/1382, and has been resolved.  There will be a new release of conda-build soon.

**Closed** 2016-09-27 15:12 UTC

**Comment by blankclemens** [comment] 2016-09-27 15:37
Thanks a lot for the fast reply and sorry that I couldn't identify this as the duplicate. For the moment, downgrading to conda-build 1.21.14 works for me.
