### ISSUE TITLE
Wheel output not picking up shared libraries

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2736] opened 2018-03-05 23:05 UTC
Tried building a wheel that relied on a shared library as shown in PR ( https://github.com/conda-forge/python-snappy-feedstock/pull/12 ). While the build worked, it did not package the shared library, which meant the wheel didn't work properly when importing in the installed environment. Not sure how the wheel folks detect and solve this problem, but guessing there's something else we need to do.

**Comment by msarahan** [comment] 2018-03-06 00:27
duplicate of https://github.com/conda/conda-build/issues/1706 - closing.  Some combination of auditwheel and delocate.  Maybe we can sort this out at scipy with one of the wheel advocates.

**Closed by msarahan** 2018-03-06 00:27 UTC

**Comment by jakirkham** [comment] 2018-03-06 00:44
Sorry for the dup. That sounds like what I have read as well. Sounds good.
