### ISSUE TITLE
3.0.4 reports conflicting numpy version

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [conda/conda-build#2191] opened 2017-07-12 15:10 UTC
Going from conda build 2.1.15-py36_0 to 3.0.4-py36_0 broke our build; conda build reports a conflicting numpy version between numpy=1.11 and the numpy that our recipe actually demands. Explicitly setting the numpy version in the conda-build command seems to solve our problem... But why not just pick up our preferred numpy version from the recipe, instead of having to repeat that? This strikes us as more than a bug than a feature.

Or is  it?

**Comment by msarahan** [comment] 2017-07-12 15:27
This sounds like a bug to me.  Can you show a minimal reproducing recipe?

**Comment by EelcoHoogendoorn** [comment] 2017-07-12 15:40
Hmm probably not; the build relies on some custom built packages on our private channel; none of which demand the supposedly conflicting numpy version, but the fact that this problem hasnt been reported more widely yet suggests it is an interaction at that level, I suppose. Will let you know if we learn more about the problem.

**Comment by msarahan** [comment] 2017-07-12 15:42
OK.  If you manage to track it down, I'll be happy to fix it.  Conda-build does try to fill in numpy versions when there's a value in the "variant" - but should only be doing this when there is not already a version associated with that numpy spec.  This is done with a regex, and there may be a bug in the regex.  Unfortunately, without seeing how you're specifying numpy, it's much harder to figure out how that regex might be going wrong.

**Comment by EelcoHoogendoorn** [comment] 2017-07-12 15:45
Happens on both linux and windows builds, btw

**Comment by msarahan** [comment] 2017-07-12 20:31
I think #2193 may fix this, but I'd appreciate if you could test it or provide a recipe that reproduces your error.

**Comment by mcflugen** [comment] 2017-07-12 21:43
@msarahan: I can give a minimal example that reproduces the problem I'm seeing, which, I think is the same as the issue being reported here.

`meta.yaml`:
```yaml
package:
  name: foobar

requirements:
  build:
    - numpy x.x
```

If I then run,
```bash
$ conda build .
```
I get an error that ends in,
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['numpy']
```
If I drop the `x.x` or use an older version of `conda-build`, the above error goes away.

**Comment by msarahan** [comment] 2017-07-12 21:58
Thanks @mcflugen - that is exactly the error fixed by #2193.  Since this is such a major bug, I'll get the next release out tonight.

**Comment by msarahan** [comment] 2017-07-12 21:59
Fixed by #2193.  Closing.

**Comment by mcflugen** [comment] 2017-07-12 22:00
Perfect! Thanks so much @msarahan!

**Closed by msarahan** 2017-07-12 21:59 UTC

**Comment by msarahan** [comment] 2017-07-12 23:35
3.0.5 should be available.  Please let me know if you have further issues.

**Comment by Korijn** [comment] 2017-07-13 07:15
It still doesn't work for us...

```
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
Failed to get install actions, max retries exceeded.
ERROR:conda_build.environ:Failed to get install actions, max retries exceeded.
[INVOKE] Building...
The following NEW packages will be INSTALLED:
    cython:         0.25.2-py36_0 defaults
    mkl:            2017.0.3-0    defaults
    numpy:          1.12.1-py36_0 defaults
    pip:            9.0.1-py36_1  defaults
    python:         3.6.1-2       defaults
    pyyaml:         3.12-py36_0   defaults
    setuptools:     27.2.0-py36_1 defaults
    vs2015_runtime: 14.0.25420-0  defaults
    wheel:          0.29.0-py36_0 defaults
source tree in: C:\Miniconda36-x64\conda-bld\scikit-clinicalgraphics_1499929248833\work
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 700, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 865, in solve
    self.find_conflicts(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 371, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 700, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 865, in solve
    self.find_conflicts(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 371, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 700, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 865, in solve
    self.find_conflicts(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 371, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 999, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 481, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1617, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 622, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 262, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 104, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 736, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 736, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 736, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 700, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 865, in solve
    self.find_conflicts(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 371, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
Use "conda info <package>" to see the dependencies for each package.
Command exited with code 1
```

Conda info output:

```
Current conda install:
               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 3.0.5
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Miniconda36-x64  (writable)
    default environment : C:\Miniconda36-x64
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/3.6.0 Windows/2012ServerR2 Windows/6.3.9600    
          administrator : True
# conda environments:
#
root                  *  C:\Miniconda36-x64
sys.version: 3.6.0 |Continuum Analytics, Inc.| (defau...
sys.prefix: C:\Miniconda36-x64
sys.executable: C:\Miniconda36-x64\python.exe
conda location: C:\Miniconda36-x64\lib\site-packages\conda
conda-build: C:\Miniconda36-x64\Scripts\conda-build.exe
conda-convert: C:\Miniconda36-x64\Scripts\conda-convert.exe
conda-develop: C:\Miniconda36-x64\Scripts\conda-develop.exe
conda-env: C:\Miniconda36-x64\Scripts\conda-env.exe
conda-index: C:\Miniconda36-x64\Scripts\conda-index.exe
conda-inspect: C:\Miniconda36-x64\Scripts\conda-inspect.exe
conda-metapackage: C:\Miniconda36-x64\Scripts\conda-metapackage.exe
conda-render: C:\Miniconda36-x64\Scripts\conda-render.exe
conda-server: C:\Miniconda36-x64\Scripts\conda-server.exe
conda-skeleton: C:\Miniconda36-x64\Scripts\conda-skeleton.exe
conda-verify: C:\Miniconda36-x64\Scripts\conda-verify.exe
user site dirs: 
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Miniconda36-x64\Library\bin;C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial;;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent
PYTHONHOME: <not set>
PYTHONPATH: <not set>
WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by Korijn** [comment] 2017-07-13 07:19
So here's a minimal reproduction:

meta.yaml:

```
package:
  name: foobar

requirements:
  build:
    - numpy 1.12.1
```

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.12.1.*
```

**Comment by EelcoHoogendoorn** [comment] 2017-07-13 07:23
@msarahan could you reopen this issue, given the new information? Thanks
